(()=>{'use strict';const form=document.getElementById('brief-form');if(!form)return;
const output=document.getElementById('brief-output'),send=document.getElementById('brief-send'),status=document.getElementById('brief-status');
const guides={website:{label:'A website that does more',build:'One focused page with a clear offer, useful proof, and one primary visitor action.',steps:['Choose the audience and the action you want them to take.','Write the offer and build a mobile-friendly first page.','Connect the inquiry or booking handoff and test it end to end.'],measure:'Qualified inquiries or bookings per visit.'},campaign:{label:'A marketing campaign',build:'One audience, one offer, one landing page, and a measurable response path.',steps:['Choose a specific audience, offer, and test budget.','Create the message, creative, landing page, and follow-up.','Test tracking and response handling before launching.'],measure:'Cost per qualified inquiry and the rate of inquiries becoming customers.'},automation:{label:'An automated workflow',build:'One repeatable task with a clear trigger, an action, and a human fallback.',steps:['Map how the task works today and where it gets stuck.','Connect the smallest useful workflow with the right permissions.','Test success, failure, and duplicate inputs before turning it on.'],measure:'Time saved, successful completions, and exceptions needing attention.'},shop:{label:'An online store',build:'A focused product offer with working checkout, order handling, and customer support.',steps:['Choose the product, audience, fulfillment plan, and margin.','Build the product page, checkout, shipping, and return information.','Run a test order and confirm every handoff before promotion.'],measure:'Purchase conversion, margin after acquisition costs, and repeat purchases.'},tool:{label:'An interactive tool',build:'A small calculator, planner, comparison, or guided experience that gives visitors a useful result.',steps:['Choose one question your customers repeatedly ask.','Define the inputs and build the simplest useful result.','Test real examples and add an optional handoff to your team.'],measure:'Tool completions and the share of users who request a next step.'}};
Object.assign(guides,{
 audit:{label:'A website or marketing audit',build:'An audit request focused on the pages, campaigns, or customer journey you want reviewed.',steps:['Share the website, audience, and the problem you want investigated.','List the channels and metrics you already use; do not include passwords.','Agree the scope and deliverable with Kyle before the review starts.'],measure:'A prioritized list of improvements with a baseline for measuring their effect.'},
 podcast:{label:'A podcast or interview request',build:'An invitation with enough context to decide whether the conversation is a good fit.',steps:['Share the show name, audience, and a link to a recent episode.','Suggest the topic, format, recording length, and preferred dates with your time zone.','Confirm availability, recording details, and publication plans with Kyle.'],measure:'A confirmed topic and recording time, with clear next steps for both sides.'},
 booking:{label:'A conversation with Kyle',build:'A meeting request with a clear purpose and the information needed to arrange a useful conversation.',steps:['Describe the topic and the outcome you want from the conversation.','Suggest two or three dates, your time zone, and who should attend.','Wait for Kyle to confirm availability; this brief does not reserve a time.'],measure:'A confirmed meeting with a clear agenda.'}
});
const hints={podcast:'Include your show, audience, topic, recording format, preferred dates, and time zone.',booking:'Include the purpose, attendees, preferred dates, and time zone. This prepares a request, not a confirmed booking.',audit:'Include your website, channels to review, and the main issue. Never share passwords or access keys.'};
function setContext(){const type=document.getElementById('brief-type').value,hint=document.getElementById('request-hint');hint.textContent=hints[type]||'';hint.hidden=!hints[type];}
document.getElementById('brief-type').addEventListener('change',setContext);
document.querySelectorAll('[data-request]').forEach(link=>link.addEventListener('click',()=>{document.getElementById('brief-type').value=link.dataset.request;setContext();document.getElementById('brief-goal').focus({preventScroll:true});track('ee_request_open');}));
function track(event){window.dataLayer=window.dataLayer||[];window.dataLayer.push({event,tenant_id:'KG',tool:'idea_lab',project_type:document.getElementById('brief-type').value});}
function sync(){send.href='mailto:kyleg@marketingapes.com?subject='+encodeURIComponent('Let’s build this — project brief')+'&body='+encodeURIComponent(output.value);}
form.addEventListener('submit',e=>{e.preventDefault();const goal=document.getElementById('brief-goal').value.trim();if(!goal){document.getElementById('brief-goal').focus();return;}const g=guides[document.getElementById('brief-type').value],business=document.getElementById('brief-site').value.trim();output.value=['MY NEXT MOVE',business?'Business / website: '+business:'','Project: '+g.label,'','THE OUTCOME I WANT',goal,'','A STARTING POINT',g.build,'','FIRST THREE STEPS',...g.steps.map((s,i)=>(i+1)+'. '+s),'','WHAT TO MEASURE',g.measure,'','TO WORK OUT WITH KYLE','Audience, existing tools, timeline, budget, and who owns each step.','','This is a template-based starting brief, not a quote or a finished strategy.'].filter((v,i,a)=>v!==''||a[i-1]!=='').join('\n');sync();document.getElementById('brief-result').hidden=false;status.textContent='Your starting brief is ready. Edit it below.';track('ee_brief_generated');output.focus({preventScroll:false});});
output.addEventListener('input',sync);
document.getElementById('brief-copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(output.value);status.textContent='Brief copied.';track('ee_brief_copy');}catch{output.focus();output.select();status.textContent='Select and copy the brief using your device’s copy command.';}});
document.getElementById('brief-download').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([output.value],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='my-next-move.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='Brief download started.';track('ee_brief_download');});send.addEventListener('click',()=>{sync();track('ee_brief_email_open');});
document.querySelectorAll('[data-social="linkedin"]').forEach(a=>a.addEventListener('click',()=>{window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:'ee_social_click',tenant_id:'KG',social_platform:'linkedin',destination:a.href});}));
})();
