#!/bin/sh
set -eu

# Decode committed base64 assets on both GNU/Linux (Render) and macOS.
# Keep the source files so local verification does not dirty the checkout.
find . -name "*.b64" -type f | while IFS= read -r source; do
  output=${source%.b64}
  temporary="${output}.tmp.$$"
  # Reading from stdin works with GNU coreutils and macOS base64.
  base64 --decode < "$source" > "$temporary"
  mv "$temporary" "$output"
done
echo "b64 decode done"

# Hook URLs are secrets and never live in the repo. Each Render static site sets env vars named
#   EE_HOOK_<TENANT>_<NAME>=https://...      (e.g. EE_HOOK_NIL_INTAKE, EE_HOOK_LFMA_ORDER)
# and this step writes <tenant>/ee/runtime.js (gitignored) exposing window.EE_RUNTIME.hooks.<name>.
# Only variables carrying THIS tenant's prefix reach that tenant's file - tenant isolation by construction.
# A stocked tenant with no hook vars still gets a runtime.js with an empty hook map, so pages fail closed, not 404.
json_escape() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }
for dir in */; do
  dir=${dir%/}
  [ -f "$dir/ee/site.json" ] || [ -f "$dir/domain.json" ] || continue
  tenant=$(printf '%s' "$dir" | tr '[:lower:]' '[:upper:]')
  prefix="EE_HOOK_${tenant}_"
  hooks=""
  for entry in $(env | grep "^${prefix}" | cut -d= -f1 | sort || true); do
    name=$(printf '%s' "${entry#"$prefix"}" | tr '[:upper:]' '[:lower:]')
    value=$(eval "printf '%s' \"\$$entry\"")
    case "$value" in https://*) ;; *) echo "skip $entry: not an https URL" >&2; continue ;; esac
    [ -n "$hooks" ] && hooks="$hooks,"
    hooks="$hooks\"$(json_escape "$name")\":\"$(json_escape "$value")\""
  done
  # Authoritative suppression endpoint (engine-provided): EE_SUPPRESSION_<TENANT>_ENDPOINT=https://...
  # Without it every outbound gate answers "BLOCK - authoritative suppression check unavailable".
  sep=$(eval "printf '%s' \"\${EE_SUPPRESSION_${tenant}_ENDPOINT:-}\"")
  case "$sep" in https://*) sep="\"$(json_escape "$sep")\"" ;; *) sep="null" ;; esac
  if [ -n "$hooks" ] || [ -f "$dir/ee/site.json" ]; then
    mkdir -p "$dir/ee"
    printf '/* generated by build.sh from Render env - never commit */\nwindow.EE_RUNTIME=Object.freeze({tenant_id:"%s",hooks:Object.freeze({%s}),suppression_endpoint:%s});\n' "$tenant" "$hooks" "$sep" > "$dir/ee/runtime.js"
  fi
done
echo "runtime hooks done"
