#!/bin/sh
set -eu

# Decode committed base64 assets on both GNU/Linux (Render) and macOS.
# Keep the source files so local verification does not dirty the checkout.
find . -name "*.b64" -type f | while IFS= read -r source; do
  output=${source%.b64}
  temporary="${output}.tmp.$$"
  # Reading from stdin works with GNU coreutils and macOS base64.
  base64 --decode < "$source" > "$temporary"
  mv "$temporary" "$output"
done
echo "b64 decode done"

# /ee/runtime.js is PUBLIC, page-readable state. It therefore carries NO provider destination and NO credential:
#   tenant_id            - this tenant
#   actions              - logical action names the engine will accept for this tenant (EE_ACTIONS_<TENANT>_NAMES=intake,lead)
#   actions_endpoint     - the governed Evolution Engine actions endpoint (EE_ACTIONS_<TENANT>_ENDPOINT=https://...)
#   suppression_endpoint - the engine's authoritative suppression endpoint (EE_SUPPRESSION_<TENANT>_ENDPOINT=https://...)
# Provider webhook URLs (Zapier/Make/...) belong ONLY to the engine. If a legacy EE_HOOK_<TENANT>_<NAME> variable is still
# set on a static site, its NAME is kept as a configured action and its VALUE is discarded with a warning - it is never
# written into the served tree. Without an actions endpoint every outbound action fails closed.
json_escape() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }
for dir in */; do
  dir=${dir%/}
  [ -f "$dir/ee/site.json" ] || [ -f "$dir/domain.json" ] || continue
  tenant=$(printf '%s' "$dir" | tr '[:lower:]' '[:upper:]')
  names=""
  add_name() {
    n=$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9_')
    [ -n "$n" ] || return 0
    case ",$names," in *",$n,"*) return 0 ;; esac
    names="${names:+$names,}$n"
  }
  declared=$(eval "printf '%s' \"\${EE_ACTIONS_${tenant}_NAMES:-}\"")
  for n in $(printf '%s' "$declared" | tr ',' ' '); do add_name "$n"; done
  prefix="EE_HOOK_${tenant}_"
  for entry in $(env | grep "^${prefix}" | cut -d= -f1 | sort || true); do
    echo "warn $entry: provider hook URLs are never emitted to the page; kept as action name only - move the URL to the engine" >&2
    add_name "${entry#"$prefix"}"
  done
  aep=$(eval "printf '%s' \"\${EE_ACTIONS_${tenant}_ENDPOINT:-}\"")
  case "$aep" in https://*) aep="\"$(json_escape "$aep")\"" ;; *) aep="null" ;; esac
  sep=$(eval "printf '%s' \"\${EE_SUPPRESSION_${tenant}_ENDPOINT:-}\"")
  case "$sep" in https://*) sep="\"$(json_escape "$sep")\"" ;; *) sep="null" ;; esac
  actions=""
  for n in $(printf '%s' "$names" | tr ',' ' '); do actions="${actions:+$actions,}\"$n\""; done
  if [ -n "$names" ] || [ -f "$dir/ee/site.json" ]; then
    mkdir -p "$dir/ee"
    printf '/* generated by build.sh from Render env - never commit. Contains NO provider destination and NO credential. */\nwindow.EE_RUNTIME=Object.freeze({tenant_id:"%s",actions:Object.freeze([%s]),actions_endpoint:%s,suppression_endpoint:%s});\n' "$tenant" "$actions" "$aep" "$sep" > "$dir/ee/runtime.js"
  fi
done
echo "runtime config done"
