import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {Script} from 'node:vm';
const html=readFileSync(new URL('../lfma/portal/prototypes/client-perspective-directions/04-campaign-portal.html',import.meta.url),'utf8');
test('campaign portal remains offline and excludes private source interfaces',()=>{assert.doesNotMatch(html,/https?:\/\/|1FET1|evidence_url|lead_id|fetch\(|XMLHttpRequest|sendBeacon|localStorage|<form/);assert.match(html,/Prototype · Not live/);});
test('exact requested campaign and section navigation is present with neutral Handoff',()=>{for(const key of ['mva','la','handoff'])assert.match(html,new RegExp('data-campaign="'+key+'"'));for(const key of ['overview','leads','marketing','next'])assert.match(html,new RegExp('data-section="'+key+'"'));assert.match(html,/Label to confirm/);assert.match(html,/Historical proof is not reused as current campaign data/);});
test('actual spending and remaining budget are unknown rather than derived from plan',()=>{assert.match(html,/data-metric="spent"[\s\S]*?metric-number">—/);assert.match(html,/data-metric="remaining"[\s\S]*?metric-number">—/);assert.match(html,/Unknown until actual spend is verified/);assert.match(html,/Budget allocation, not actual spend/);});
test('lead examples are explicitly synthetic and kept out of live totals',()=>{assert.match(html,/These are synthetic, deidentified examples/);assert.match(html,/Demo rows are excluded from all overview totals/);assert.match(html,/DEMO-01/);assert.doesNotMatch(html,/first_name|last_name|[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i);});
test('attempts, AI connection, transfer and firm proof stages remain distinct',()=>{for(const stage of ['Called / attempted','Connected to AI','Transfer attempted','Transfer completed','Phillips connected / working','Firm disposition / Signed proof'])assert.ok(html.includes(stage));assert.match(html,/attempt is not a connection/);assert.match(html,/no executed-retainer proof/);});
test('planned graph, unknown results and proposed optimization are truthful',()=>{assert.match(html,/Meta Website 3000 dollars, 60 percent; Google Search 2000 dollars, 40 percent/);assert.match(html,/No verified spend or results series connected/);assert.match(html,/Prepared drafts are not counted as executed optimizations/);assert.match(html,/No measured performance effect is claimed/);});
test('asset packaging preserves headings, valid script and reduced-motion handling',()=>{assert.match(html,/CREATIVE & DESTINATION/);const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)];assert.equal(scripts.length,1);assert.doesNotThrow(()=>new Script(scripts[0][1]));assert.match(html,/data:image\/jpeg;base64,/);assert.match(html,/prefers-reduced-motion:reduce/);});

test('eight highlighted measures drill into evidence without fake counters',()=>{for(const key of ['budget','spent','remaining','leads','ai','phillips','transfers','signed'])assert.match(html,new RegExp('data-metric="'+key+'"'));assert.match(html,/function drillMetric/);assert.match(html,/METRIC PERSPECTIVE/);assert.match(html,/Remaining may be calculated only when actual spend is verified/);assert.doesNotMatch(html,/setInterval|Math\.random|requestAnimationFrame/);});

test('AI intake centerpiece links only to marked demo work and makes no legal eligibility decision',()=>{assert.match(html,/AI INTAKE · THE WORK BEHIND THE LEAD/);assert.match(html,/Every handoff/);assert.match(html,/id="explore-ai-demo"/);assert.match(html,/They do not establish actual AI work, a firm connection or legal eligibility/);assert.match(html,/Receiving acknowledgement unverified/);});

test('unified Sofia channels preserve unavailable live bindings, evidence stages and firm-reason privacy',()=>{assert.match(html,/Text\/email are OFF\/PENDING in inspected staged policy/);for(const label of ['Lead','Text','Email','Call','Status','Ad'])assert.ok(html.includes("['"+label+"',"));for(const state of ['Attempted','Sent','Delivered','Replied'])assert.ok(html.includes("['"+state+"',"));assert.match(html,/Sent, delivered, replied and connected are separate evidence states/);assert.match(html,/Firm outcome · Signed reason/);assert.match(html,/Actual firm reasons require authorized firm access/);assert.match(html,/Awaiting firm feedback/);assert.match(html,/STOP\/unsubscribe/);});

test('call evidence affordance never exposes recordings or claims provider association',()=>{assert.match(html,/Call evidence · recording \/ transcript/);assert.match(html,/Twilio \/ CallRail \/ Vapi/);assert.match(html,/synthetic identifier/);assert.match(html,/recording.disabled=true/);assert.match(html,/transcript.disabled=true/);assert.match(html,/ambiguous phone-only matching cannot attach evidence/);assert.match(html,/authorized server resolution/);assert.doesNotMatch(html,/<audio|<video|bearer|access_token|recording_url/i);});


test('reusable preview configuration separates brand/client/campaign facts from synthetic records',()=>{const cfg=JSON.parse(readFileSync(new URL('../tools/phillips-portal-prototype/campaign-portal-config.json',import.meta.url)));const fixture=JSON.parse(readFileSync(new URL('../tools/phillips-portal-prototype/campaign-portal-demo-leads.json',import.meta.url)));assert.equal(cfg.mode,'LOCAL_VISUAL_REVIEW_ONLY');assert.equal(cfg.runtime_connected,false);assert.equal(cfg.plan.actual_spent,null);assert.equal(cfg.plan.remaining,null);assert.equal(cfg.plan.total_usd,cfg.plan.meta_website_usd+cfg.plan.google_search_usd);assert.equal(fixture.mode,'SYNTHETIC_ONLY');assert.equal(fixture.counted_in_actual_totals,false);assert.equal(fixture.rows.length,3);assert.equal(cfg.client.tenant_id,'phillips');});

test('historical campaign images stay separate from live performance and individual lead attribution',()=>{assert.match(html,/HISTORICAL CAMPAIGN REFERENCE/);assert.match(html,/Archived August21 briefing/);assert.match(html,/Archived May7 Best Tort Lawyers/);assert.match(html,/individual lead attribution unavailable/);assert.match(html,/not current approval, verified delivery/);assert.match(html,/gallery.hidden=!asset/);});

test('task review card shows actual staged creative and truthful unassigned approval state',()=>{assert.match(html,/Creative review sample/);assert.match(html,/Exact staged artwork/);assert.match(html,/Approval unverified/);assert.match(html,/not an assigned request or approval action/);assert.match(html,/creative-review-sample/);});

test('historical dispatch evidence does not fabricate unique people, current totals or Signed',()=>{const h=JSON.parse(readFileSync(new URL('../tools/phillips-portal-prototype/historical-summary.json',import.meta.url)));assert.equal(h.dispatch_evidence_events,h.api_success_events+h.email_lead_record_events);assert.equal(h.dispatch_evidence_events,Object.values(h.campaign_events).reduce((a,b)=>a+b,0));assert.equal(h.dispatch_evidence_events,h.dated_events+h.undated_la_api_events);assert.equal(h.separate_firm_intakes.total,h.separate_firm_intakes.marketing_apes+h.separate_firm_intakes.deadleads);assert.equal(h.unique_people_total,null);assert.equal(h.actual_signed_total,null);assert.equal(h.current_campaign_totals,false);assert.equal(h.coverage,'INCOMPLETE');assert.match(html,/not unique people, qualified conversations or verified firm receipts/);assert.match(html,/actual Signed total remains unknown/);});

test('all135 deidentified historical records have honest counts and no contact/source keys',()=>{const h=JSON.parse(readFileSync(new URL('../tools/phillips-portal-prototype/deidentified-dispatch-history.json',import.meta.url)));assert.equal(h.rows.length,135);assert.equal(h.rows.filter(r=>r.received_at).length,78);assert.equal(h.rows.filter(r=>r.dispatch_at).length,97);assert.equal(h.rows.filter(r=>r.campaign==='mva').length,39);assert.equal(h.rows.filter(r=>r.campaign==='la').length,93);assert.equal(h.rows.filter(r=>r.firm_match==='Explicit current-report crosswalk').length,96);assert.equal(h.private_bytes_verified_locally,true);assert.equal(h.actual_signed_total,null);for(const row of h.rows){for(const key of ['name','phone','email','source_lead_id','firm_intake_id','source_email_id','source_row','source_url','provenance'])assert.ok(!(key in row));assert.equal(row.signed,'Not verified');}assert.match(html,/View all 135 historical dispatch events/);assert.match(html,/received_at/);assert.match(html,/dispatch_timezone_basis/);});

test('yearwide account coverage remains pending and dedupe retains all evidence events',()=>{const h=JSON.parse(readFileSync(new URL('../tools/phillips-portal-prototype/deidentified-dispatch-history.json',import.meta.url)));assert.equal(h.complete_all_accounts,false);assert.equal(h.yearwide_account_coverage,'INVENTORY_PENDING');assert.deepEqual(h.requested_period,{start:'2026-01-01',through:'2026-10-04'});assert.equal(h.distinct_explicit_source_groups,119);assert.equal(h.missing_source_id_events,14);assert.equal(h.rows.length,135);assert.equal(h.rows.every(r=>r.account_key==='UNVERIFIED'),true);assert.match(html,/account.disabled=true/);assert.match(html,/id='history-source'/);});
