import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {Script} from 'node:vm';
const html=readFileSync(new URL('../lfma/portal/prototypes/client-perspective-directions/04-campaign-portal.html',import.meta.url),'utf8');
test('campaign portal remains offline and excludes private source interfaces',()=>{assert.doesNotMatch(html,/https?:\/\/|1FET1|evidence_url|lead_id|fetch\(|XMLHttpRequest|sendBeacon|localStorage|<form/);assert.match(html,/Prototype · Not live/);});
test('exact requested campaign and section navigation is present with neutral Handoff',()=>{for(const key of ['mva','la','handoff'])assert.match(html,new RegExp('data-campaign="'+key+'"'));for(const key of ['overview','leads','marketing','next'])assert.match(html,new RegExp('data-section="'+key+'"'));assert.match(html,/Label to confirm/);assert.match(html,/Historical proof is not reused as current campaign data/);});
test('actual spending and remaining budget are unknown rather than derived from plan',()=>{assert.match(html,/Actual spent<\/div><div class="value unknown">Unknown/);assert.match(html,/Remaining<\/div><div class="value unknown">Unknown/);assert.match(html,/Needs verified actual spend/);assert.match(html,/Budget allocation, not actual spend/);});
test('lead examples are explicitly synthetic and kept out of live totals',()=>{assert.match(html,/These are synthetic, deidentified examples/);assert.match(html,/Demo rows are excluded from all overview totals/);assert.match(html,/DEMO-01/);assert.doesNotMatch(html,/first_name|last_name|phone|email/);});
test('attempts, AI connection, transfer and firm proof stages remain distinct',()=>{for(const stage of ['Called / attempted','Connected to AI','Transfer attempted','Transfer completed','Phillips connected / working','Firm disposition / Signed proof'])assert.ok(html.includes(stage));assert.match(html,/attempt is not a connection/);assert.match(html,/no executed-retainer proof/);});
test('planned graph, unknown results and proposed optimization are truthful',()=>{assert.match(html,/Meta Website 3000 dollars, 60 percent; Google Search 2000 dollars, 40 percent/);assert.match(html,/No verified spend or results series connected/);assert.match(html,/Prepared drafts are not counted as executed optimizations/);assert.match(html,/No measured performance effect is claimed/);});
test('asset packaging preserves headings, valid script and reduced-motion handling',()=>{assert.match(html,/CREATIVE & DESTINATION/);const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)];assert.equal(scripts.length,1);assert.doesNotThrow(()=>new Script(scripts[0][1]));assert.match(html,/data:image\/jpeg;base64,/);assert.match(html,/prefers-reduced-motion:reduce/);});
