import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {Script} from 'node:vm';
const html=readFileSync(new URL('../lfma/portal/prototypes/client-perspective-directions/04-campaign-portal.html',import.meta.url),'utf8');
test('campaign portal remains offline and excludes private source interfaces',()=>{assert.doesNotMatch(html,/https?:\/\/|1FET1|evidence_url|lead_id|fetch\(|XMLHttpRequest|sendBeacon|localStorage|<form/);assert.match(html,/Prototype · Not live/);});
test('exact requested campaign and section navigation is present with neutral Handoff',()=>{for(const key of ['mva','la','handoff'])assert.match(html,new RegExp('data-campaign="'+key+'"'));for(const key of ['overview','leads','marketing','next'])assert.match(html,new RegExp('data-section="'+key+'"'));assert.match(html,/Label to confirm/);assert.match(html,/Historical proof is not reused as current campaign data/);});
test('actual spending and remaining budget are unknown rather than derived from plan',()=>{assert.match(html,/data-metric="spent"[\s\S]*?metric-number">—/);assert.match(html,/data-metric="remaining"[\s\S]*?metric-number">—/);assert.match(html,/Unknown until actual spend is verified/);assert.match(html,/Budget allocation, not actual spend/);});
test('lead examples are explicitly synthetic and kept out of live totals',()=>{assert.match(html,/These are synthetic, deidentified examples/);assert.match(html,/Demo rows are excluded from all overview totals/);assert.match(html,/DEMO-01/);assert.doesNotMatch(html,/first_name|last_name|[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i);});
test('attempts, AI connection, transfer and firm proof stages remain distinct',()=>{for(const stage of ['Called / attempted','Connected to AI','Transfer attempted','Transfer completed','Phillips connected / working','Firm disposition / Signed proof'])assert.ok(html.includes(stage));assert.match(html,/attempt is not a connection/);assert.match(html,/no executed-retainer proof/);});
test('planned graph, unknown results and proposed optimization are truthful',()=>{assert.match(html,/Meta Website 3000 dollars, 60 percent; Google Search 2000 dollars, 40 percent/);assert.match(html,/No verified spend or results series connected/);assert.match(html,/Prepared drafts are not counted as executed optimizations/);assert.match(html,/No measured performance effect is claimed/);});
test('asset packaging preserves headings, valid script and reduced-motion handling',()=>{assert.match(html,/CREATIVE & DESTINATION/);const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)];assert.equal(scripts.length,1);assert.doesNotThrow(()=>new Script(scripts[0][1]));assert.match(html,/data:image\/jpeg;base64,/);assert.match(html,/prefers-reduced-motion:reduce/);});

test('eight highlighted measures drill into evidence without fake counters',()=>{for(const key of ['budget','spent','remaining','leads','ai','phillips','transfers','signed'])assert.match(html,new RegExp('data-metric="'+key+'"'));assert.match(html,/function drillMetric/);assert.match(html,/METRIC PERSPECTIVE/);assert.match(html,/Remaining may be calculated only when actual spend is verified/);assert.doesNotMatch(html,/setInterval|Math\.random|requestAnimationFrame/);});

test('AI intake centerpiece links only to marked demo work and makes no legal eligibility decision',()=>{assert.match(html,/AI INTAKE · THE WORK BEHIND THE LEAD/);assert.match(html,/Every handoff/);assert.match(html,/id="explore-ai-demo"/);assert.match(html,/They do not establish actual AI work, a firm connection or legal eligibility/);assert.match(html,/Receiving acknowledgement unverified/);});

test('unified Sofia channels preserve unavailable live bindings, evidence stages and firm-reason privacy',()=>{assert.match(html,/Text\/email are OFF\/PENDING in inspected staged policy/);for(const label of ['Lead','Text','Email','Call','Status','Ad'])assert.ok(html.includes("['"+label+"',"));for(const state of ['Attempted','Sent','Delivered','Replied'])assert.ok(html.includes("['"+state+"',"));assert.match(html,/Sent, delivered, replied and connected are separate evidence states/);assert.match(html,/Firm outcome · Signed reason/);assert.match(html,/Actual firm reasons require authorized firm access/);assert.match(html,/Awaiting firm feedback/);assert.match(html,/STOP\/unsubscribe/);});

test('call evidence affordance never exposes recordings or claims provider association',()=>{assert.match(html,/Call evidence · recording \/ transcript/);assert.match(html,/Twilio \/ CallRail \/ Vapi/);assert.match(html,/synthetic identifier/);assert.match(html,/recording.disabled=true/);assert.match(html,/transcript.disabled=true/);assert.match(html,/ambiguous phone-only matching cannot attach evidence/);assert.match(html,/authorized server resolution/);assert.doesNotMatch(html,/<audio|<video|bearer|access_token|recording_url/i);});


test('reusable preview configuration separates brand/client/campaign facts from synthetic records',()=>{const cfg=JSON.parse(readFileSync(new URL('../tools/phillips-portal-prototype/campaign-portal-config.json',import.meta.url)));const fixture=JSON.parse(readFileSync(new URL('../tools/phillips-portal-prototype/campaign-portal-demo-leads.json',import.meta.url)));assert.equal(cfg.mode,'LOCAL_VISUAL_REVIEW_ONLY');assert.equal(cfg.runtime_connected,false);assert.equal(cfg.plan.actual_spent,null);assert.equal(cfg.plan.remaining,null);assert.equal(cfg.plan.total_usd,cfg.plan.meta_website_usd+cfg.plan.google_search_usd);assert.equal(fixture.mode,'SYNTHETIC_ONLY');assert.equal(fixture.counted_in_actual_totals,false);assert.equal(fixture.rows.length,3);assert.equal(cfg.client.tenant_id,'phillips');});

test('historical campaign images stay separate from live performance and individual lead attribution',()=>{assert.match(html,/HISTORICAL CAMPAIGN REFERENCE/);assert.match(html,/Archived August21 briefing/);assert.match(html,/Archived May7 Best Tort Lawyers/);assert.match(html,/individual lead attribution unavailable/);assert.match(html,/not current approval, verified delivery/);assert.match(html,/gallery.hidden=!asset/);});
