import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {mount, locationError, examples} from '../lfma/lead-verification/verification.mjs';
function fixture({secure=true,supported=true}={}){
 const nodes=new Map();
 const node=()=>({textContent:'',hidden:false,disabled:false,children:[],events:{},dataset:{},addEventListener(name,fn){this.events[name]=fn;},setAttribute(name,value){this[name]=value;},append(...children){this.children.push(...children);},replaceChildren(...children){this.children=children;},focus(){this.focused=true;}});
 const choices=Object.keys(examples).map(key=>{const el=node();el.dataset.example=key;return el;});
 const doc={getElementById(id){if(!nodes.has(id))nodes.set(id,node());return nodes.get(id);},createElement:node,querySelectorAll:()=>choices};
 const requests=[];const nav={language:'en-US',userAgent:'Test',...(supported?{geolocation:{getCurrentPosition(ok,fail,options){requests.push({ok,fail,options});}}}:{})};
 mount(doc,nav,{innerWidth:390,innerHeight:844,isSecureContext:secure});
 return {nodes,requests,choices,click:id=>nodes.get(id).events.click()};
}
test('no location request on load; click gates request even with preexisting permission',()=>{const f=fixture();assert.equal(f.requests.length,0);f.click('location-button');assert.equal(f.requests.length,1);assert.equal(f.nodes.get('location-button').disabled,true);assert.equal(f.requests[0].options.maximumAge,0);});
for(const code of [1,2,3,99])test(`location error ${code} preserves visible retry and distinct status`,()=>{const f=fixture();f.click('location-button');f.requests[0].fail({code});assert.equal(f.nodes.get('location-button').hidden,false);assert.equal(f.nodes.get('location-button').disabled,false);assert.equal(f.nodes.get('location-status').textContent,locationError(code));assert.equal(f.nodes.get('coordinates').hidden,true);f.click('location-button');assert.equal(f.requests.length,2);});
test('synthetic location success, clearing and failed re-request never leave stale coordinates',()=>{const f=fixture();f.click('location-button');f.requests[0].ok({coords:{latitude:12.34567,longitude:23.45678,accuracy:42}});assert.match(f.nodes.get('coordinates').textContent,/12.34567/);assert.equal(f.nodes.get('clear-location').hidden,false);f.click('clear-location');assert.equal(f.nodes.get('coordinates').textContent,'');assert.equal(f.nodes.get('coordinates').hidden,true);f.click('location-button');f.requests[1].ok({coords:{latitude:12,longitude:23,accuracy:40}});f.click('location-button');f.requests[2].fail({code:3});assert.equal(f.nodes.get('coordinates').textContent,'');});
for(const options of [{secure:false},{supported:false}])test(`unsupported context ${JSON.stringify(options)} requests nothing`,()=>{const f=fixture(options);f.click('location-button');assert.equal(f.requests.length,0);assert.equal(f.nodes.get('location-button').disabled,false);assert.match(f.nodes.get('location-status').textContent,/Nothing was requested/);});
test('invalid position is handled as unavailable',()=>{const f=fixture();f.click('location-button');f.requests[0].ok({coords:{latitude:NaN,longitude:200,accuracy:1}});assert.equal(f.nodes.get('coordinates').hidden,true);assert.equal(f.nodes.get('location-status').textContent,locationError(2));});
test('fictional receipts never claim firm outcomes',()=>{const f=fixture();for(const choice of f.choices){choice.events.click();const receipt=f.nodes.get('receipt');assert.match(receipt.children[0].textContent,/Synthetic/);assert.equal(receipt.children[1].children.at(-1).textContent,'Not reported');assert.equal(choice['aria-pressed'],'true');}});
test('new page has no transmissions, storage, maps, forms or trackers',()=>{const root=new URL('../lfma/lead-verification/',import.meta.url);const html=readFileSync(new URL('index.html',root),'utf8');const js=readFileSync(new URL('verification.mjs',root),'utf8');assert.match(html,/connect-src 'none'/);assert.match(html,/frame-src 'none'/);assert.match(html,/form-action 'none'/);assert.doesNotMatch(html+js,/fetch\(|XMLHttpRequest|sendBeacon|localStorage|sessionStorage|navigator\.permissions|<iframe|<form|googletagmanager|maps\.google/i);assert.match(html,/No IP address is looked up/);});
