import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {webcrypto as crypto} from 'node:crypto';
const pages=fs.readdirSync('.').filter(p=>fs.existsSync(`${p}/preview/intake.js`));
function boot(page,{valid=true,consent=true,response=true}={}){
 const html=fs.readFileSync(`${page}/preview/index.html`,'utf8'),elements={},requests=[],status=[],hidden=[];
 for(const m of html.matchAll(/id="([^"]+)"/g))elements[m[1]]={appendChild(){},querySelectorAll(){return[]},addEventListener(){},classList:{add(){},remove(){}}};
 elements['tracking-fields'].appendChild=e=>hidden.push(e);const form=elements['sofia-form'];form.elements={company_website:{value:''},contact_consent:{checked:consent}};form.reportValidity=()=>valid;form.parentNode={appendChild:e=>status.push(e)};
 const context={window:{},document:{getElementById:id=>elements[id]||null,querySelectorAll:()=>[],querySelector:()=>null,createElement:()=>({setAttribute(){}}),referrer:'',title:'Synthetic'},location:{search:'?utm_campaign=synthetic',href:'https://example.test/preview/?utm_campaign=synthetic',origin:'https://example.test',pathname:'/preview/',hostname:'example.test'},sessionStorage:{getItem:()=>null,setItem(){}},navigator:{userAgent:'synthetic',language:'en',maxTouchPoints:0},screen:{width:100,height:100},innerWidth:100,innerHeight:100,devicePixelRatio:1,crypto,URLSearchParams,Intl,AbortController,setTimeout,clearTimeout,FormData:class{entries(){return [['full_name','Synthetic Example'],['email','synthetic@example.test'],['phone','000'],['contact_consent',consent?'on':''],...hidden.map(e=>[e.name,e.value])]}get(k){return Object.fromEntries(this.entries())[k]}},fetch:async(url,opts)=>{requests.push({url,body:JSON.parse(opts.body)});return{ok:response,status:response?200:503}}};
 vm.runInNewContext(fs.readFileSync(`${page}/preview/config.js`,'utf8'),context);
 vm.runInNewContext(fs.readFileSync(`${page}/preview/intake.js`,'utf8'),context);
 return {context,form,requests,status,submit:()=>form.onsubmit({preventDefault(){}})};
}
test('all 25 nonlegal previews boot without legal form nodes and bind submit',()=>{assert.equal(pages.length,25);for(const p of pages){const b=boot(p);assert.equal(typeof b.form.onsubmit,'function',p);assert.equal(b.requests.length,0)}});
test('required-field or missing contact consent blocks network',async()=>{for(const options of [{valid:false},{consent:false}]){const b=boot('sliq',options);await b.submit();assert.equal(b.requests.length,0)}});
test('valid nonlegal inquiry uses configured endpoint and preserves identity without legal routing claims',async()=>{const b=boot('sliq');await b.submit();assert.equal(b.requests.length,1);const r=b.requests[0];assert.equal(r.url,b.context.window.DOMAIN_CONFIG.ENDPOINT);for(const key of ['lead_id','claim_id','event_id','session_id'])assert.ok(r.body[key],key);assert.equal(r.body.domain_id,'SLIQ');assert.equal(r.body.contact_consent,true);for(const key of ['routing_hint','connection_mode','transfer_authority','ai_assistant_disclosed','call_recording_disclosed','buyer_id','route_key'])assert.equal(r.body[key],undefined,key);assert.equal(b.form.hidden,true);assert.equal(b.status.length,1);await b.submit();assert.equal(b.requests.length,1)});
test('HTTP failure keeps form available; retry reuses lead and event identities',async()=>{const b=boot('sliq',{response:false});await b.submit();await b.submit();assert.equal(b.requests.length,2);assert.equal(b.requests[0].body.lead_id,b.requests[1].body.lead_id);assert.equal(b.requests[0].body.event_id,b.requests[1].body.event_id);assert.notEqual(b.form.hidden,true);assert.equal(b.status.length,0)});
test('every generated script remains identical',()=>{assert.equal(new Set(pages.map(p=>fs.readFileSync(`${p}/preview/intake.js`,'utf8'))).size,1)});
