// Phillips portal — campaign-to-outcome tab. Offline: the shipped script runs in a vm against
// synthetic fixtures generated by the report API's own builder. No network, no real data.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';

const read = (p) => readFileSync(new URL(p, import.meta.url), 'utf8');
const SRC = read('../lfma/assets/portal/phillips-report.js');
const PAGE = read('../lfma/portal/phillips/index.html');
const sample = () => JSON.parse(read('./fixtures/phillips-portal-report.sample.json'));
const empty = () => JSON.parse(read('./fixtures/phillips-portal-report.empty.json'));

function load() {
  const window = {};
  vm.runInContext(SRC, vm.createContext({ window, Promise, Date, isFinite, isNaN, String, Array, Error }));
  return window.PhillipsReport;
}
const text = (html) => html.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ');
const R = load();

test('empty system: every figure reads Unknown, never 0 or $0', () => {
  const html = R.render(empty());
  const t = text(html);
  assert.equal((html.match(/class="oc-unk"/g) || []).length, 4 * 8, 'all 32 stage cells are unknown');
  assert.equal((html.match(/<td><b>Unknown<\/b><\/td>/g) || []).length, 4, 'spend unknown on all four rows');
  assert.doesNotMatch(html, /<b>0<\/b>|\$0\.00/);
  assert.equal((t.match(/Not connected/g) || []).length, 8, 'all eight sources not connected');
  assert.match(t, /Website callback worker: no worker has identified itself/);
  assert.match(t, /“Unknown” means no source has reported — it is not zero/);
});

test('stages render as eight separate columns in order, with pending and unknown shown as such', () => {
  const html = R.render(sample());
  const heads = [...html.matchAll(/<th>([^<]+)<\/th>/g)].map((m) => m[1]);
  const i = heads.indexOf('Submissions');
  assert.deepEqual(heads.slice(i, i + 8), ['Submissions', 'Callbacks queued', 'Calls placed', 'Intakes completed', 'Transfers attempted', 'Firm receipt verified', 'Firm accepted', 'Signed retainer confirmed']);
  const row = html.split('class="oc-row"').find((b) => b.includes('24313116842'));
  const cells = [...row.matchAll(/<td class="oc-(\w+)"><b>([^<]+)<\/b>(?:<span class="sub">([^<]*)<\/span>)?/g)].map((m) => [m[1], m[2], m[3] || '']);
  assert.deepEqual(cells.map((c) => c[1]), ['8', '8', '7', '6', '5', '4', '2', '1']);
  assert.deepEqual(cells[0], ['ok', '8', '']);
  assert.match(cells[2][2], /1 pending/);
  assert.match(cells[5][2], /4 unknown/);
  assert.match(cells[7][2], /1 pending · 5 unknown/);
  assert.match(text(row), /\$87\.46/);
  assert.match(text(row), /5 platform count, this row’s window/);
});

test('signed is only the confirmed count; Converted-without-proof is listed apart', () => {
  const t = text(R.render(sample()));
  assert.match(t, /Converted without a Matter ID and retainer date \(not counted as signed\): 1/);
  const r = sample();
  r.rows[3].stages.signed_retainer_confirmed = { count: null, state: 'pending', pending: 3, not_reached: 0, unknown: 0 };
  const row = R.render(r).split('class="oc-row"').find((b) => b.includes('24313116842'));
  assert.match(row, /<td class="oc-pend"><b>Pending<\/b><span class="sub">3 pending<\/span><\/td><\/tr>/, 'pending retainers are not shown as a count');
});

test('identity stays separate from landing domain and intake; windows are stated per row and not totalled', () => {
  const html = R.render(sample());
  const pmax = text(html.split('class="oc-row"').find((b) => b.includes('24313118384')));
  assert.match(pmax, /BTL · performance max/);
  assert.match(pmax, /Google · account 9455635555 · campaign 24313118384/);
  assert.match(pmax, /Lands on: nearestinjurylawyers\.com · intake: NIL · reports to: conversion action 7564588748 \(goal 6459301608\)/);
  assert.match(pmax, /Attribution window: 90-day click \/ 1-day view/);
  const metaWeb = text(html.split('class="oc-row"').find((b) => b.includes('120254664050830231')));
  assert.match(metaWeb, /Attribution window: 1-day click \/ none view/);
  assert.match(metaWeb, /pixel 673552078259404/);
  assert.match(text(html), /different attribution windows.*not totalled or compared across rows/);
  assert.doesNotMatch(text(html), /Total conversions|All campaigns total/i);
  assert.equal((html.match(/Configured: paused/g) || []).length, 4);
});

test('superseded campaigns never appear as rows; exclusions are stated', () => {
  const html = R.render(sample());
  for (const id of ['120254663994400231', '120254663995090231', '24318918184']) assert.ok(!html.includes(id), id);
  assert.match(text(html), /Test records: 1 · dry runs: 0 · leads from superseded campaigns: 1 · leads with no campaign identity: 1/);
});

test('source freshness shows stale and failed sign-in distinctly from fresh and not connected', () => {
  const t = text(R.render(sample()));
  assert.match(t, /Google Ads — NIL account feeds: spend, platform reported Stale .* sign-in failed/);
  assert.match(t, /Website form intake \(legal-web-lead\) feeds: submission, queued callback Fresh/);
  assert.match(t, /Phillips form-status pushback .* Not connected — never/);
});

test('unmatched firm records are listed for reconciliation with last four digits only', () => {
  const html = R.render(sample());
  assert.match(text(html), /1 firm record\(s\) could not be tied to one lead\. They are not counted anywhere above until reconciled/);
  assert.match(html, /···0000/);
  assert.ok(!html.includes('MAT-SAMPLE'), 'matter ids are not displayed in the unmatched list');
  assert.match(text(R.render(empty())), /No firm records are waiting for reconciliation/);
});

test('a malformed or hostile payload shows nothing rather than wrong numbers, and is escaped', () => {
  for (const bad of [null, {}, { schema: 'other', rows: [] }, { schema: 'ee.phillips_portal_report/v1' }]) {
    assert.match(R.render(bad), /could not be read\. Nothing is shown/);
  }
  const r = sample();
  r.rows[0].identity.brand_account = '<img src=x onerror=alert(1)>';
  r.sources[0].label = '<script>x</script>';
  r.unmatched.rows[0].raw = '"><svg onload=1>';
  r.rows[1].stages.submission = { count: '12', state: 'known' };
  r.rows[2].stages.submission = { count: 3, state: 'made_up' };
  r.rows[2].spend = { value: 55, state: 'unknown' };
  const html = R.render(r);
  assert.ok(!/<img|<script|<svg/.test(html));
  assert.equal(R.cellView({ count: '12', state: 'known' }).text, 'Unknown', 'a non-numeric count is not trusted');
  assert.equal(R.cellView({ count: 3, state: 'made_up' }).text, 'Unknown');
  assert.equal(R.cellView({ count: 0, state: 'known' }).text, '0', 'a known zero is a real zero');
  assert.equal(R.cellView({ count: 5, state: 'unknown' }).text, 'Unknown');
  assert.equal(R.cellView(undefined).text, 'Unknown');
  assert.match(text(html.split('class="oc-row"').find((b) => b.includes('24313118384'))), /Unknown/);
});

test('load: sends the token as a bearer header only, and failures show no figures', async () => {
  const el = (id) => ({ id, innerHTML: '', style: {} });
  const nodes = { 'outcome-root': el('outcome-root'), 'outcome-gate': el('outcome-gate') };
  const document = { getElementById: (id) => nodes[id] || null };
  let seen;
  const ok = async (url, init) => { seen = { url, init }; return { status: 200, ok: true, json: async () => sample() }; };
  await R.load('TOKEN-VALUE', { document, fetch: ok });
  assert.equal(seen.init.headers.Authorization, 'Bearer TOKEN-VALUE');
  assert.ok(!seen.url.includes('TOKEN-VALUE'), 'the token never goes in the URL');
  assert.equal(seen.url, 'https://legal-web-lead.onrender.com/api/v1/portal/phillips/report');
  assert.ok(nodes['outcome-root'].innerHTML.includes('Campaign to outcome'));
  assert.ok(!nodes['outcome-root'].innerHTML.includes('TOKEN-VALUE'));
  assert.equal(nodes['outcome-gate'].style.display, 'none');
  for (const [status, phrase] of [[401, /not recognized/], [404, /not available yet/], [503, /HTTP 503/]]) {
    nodes['outcome-root'].innerHTML = '';
    await R.load('t', { document, fetch: async () => ({ status, ok: false, json: async () => ({}) }) });
    assert.match(nodes['outcome-root'].innerHTML, phrase);
    assert.match(nodes['outcome-root'].innerHTML, /No figures are shown/);
    assert.ok(!nodes['outcome-root'].innerHTML.includes('oc-row'));
  }
  await R.load('t', { document, fetch: async () => { throw new Error('offline'); } });
  assert.match(nodes['outcome-root'].innerHTML, /No figures are shown/);
});

test('the page and script ship no report data, tokens or storage use', () => {
  assert.ok(!/localStorage|sessionStorage|document\.cookie/.test(SRC + PAGE), 'token is memory-only');
  const tab = PAGE.slice(PAGE.indexOf("id='tab-outcomes'"), PAGE.indexOf("id='tab-summary'"));
  assert.match(tab, /<div id='outcome-root'><\/div>/, 'the tab is empty until a token returns a report');
  assert.ok(!/\$\d|\d{6,}/.test(tab), 'no figures or ids baked into the tab');
  assert.ok(!/Bearer [A-Za-z0-9]{12,}|PORTAL_TOKEN\s*=\s*["'][^"']+/.test(SRC + PAGE));
  assert.match(PAGE, /<meta name="robots" content="noindex,nofollow">/);
  assert.match(PAGE, /cf-turnstile/, 'the existing human check is still in place');
  assert.match(PAGE, /phillips-report\.js\?v=/);
  for (const fx of [JSON.stringify(sample()), JSON.stringify(empty())]) assert.ok(!/@|\+1\d{10}|\(\d{3}\) \d{3}-\d{4}/.test(fx), 'fixtures hold no emails or phone numbers');
});
