import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createReviewService, memoryAudit, scopeHash } from '../tools/phillips-portal-prototype/service.mjs';
import { rowHash, canonicalRow, verifyRow, WORKBOOK } from '../tools/phillips-portal-prototype/sheet-contract.mjs';
const original=JSON.parse(readFileSync(new URL('../tools/phillips-portal-prototype/fixture.json',import.meta.url)));
function setup(){let fixture=structuredClone(original), revoked=false;const audit=memoryAudit();const actor={subject:'demo-reviewer',itemIds:[fixture.items[0].item_id],actions:['review_creative'],mode:'LOCAL_MOCK_ONLY',expiresAt:'2099-01-01T00:00:00Z'};
 const service=createReviewService({enabled:true,mode:'LOCAL_MOCK_ONLY',audit,readCurrent:async()=>structuredClone(fixture),resolveActor:async()=>revoked?null:actor});
 return {service,audit,fixture,actor,revoke:()=>revoked=true};}
async function input(s,patch={}){const view=await s.service.view({});return {item_id:view.items[0].item_id,decision:'approved',content_hash:view.items[0].content_hash,sheet_revision:view.sheet_revision,audit_revision:view.audit_revision,idempotency_key:'request-key-0001',...patch};}
const rejected=(promise,status)=>assert.rejects(promise,e=>e.status===status);
test('service is disabled by default and never invokes injected sources',async()=>{let called=false;await rejected(createReviewService({readCurrent:()=>called=true}).view({}),503);assert.equal(called,false);});
test('recipient projection excludes other tasks, raw workbook fields and owner-only evidence links',async()=>{const s=setup();s.fixture.items[0].phone='555-secret';s.fixture.items[0].email='private@example.com';const view=await s.service.view({actor:'demo-operator'});assert.equal(view.items.length,1);assert.equal(view.items[0].item_id,s.fixture.items[0].item_id);assert.equal(view.items[0].artifact_ref,undefined);assert.doesNotMatch(JSON.stringify(view),/555-secret|private@example/);});
test('recipient cannot decide another person’s task',async()=>{const s=setup();await rejected(s.service.decide({},await input(s,{item_id:s.fixture.items[1].item_id})),404);assert.equal((await s.audit.snapshot()).events.length,0);});
test('caller-supplied actor or time is rejected',async()=>{const s=setup();await rejected(s.service.decide({},await input(s,{actor_id:'owner',decided_at:'2099'})),400);});
test('sheet approved status does not become an approval',async()=>{const s=setup();s.fixture.items[0].status_cell='approved';assert.equal((await s.service.view({})).items[0].decision,'pending');});
test('audit records trusted actor, server time and exact version; no execution authority',async()=>{const s=setup();const result=await s.service.decide({},await input(s));assert.equal(result.execution_authorized,false);const e=(await s.audit.snapshot()).events[0];assert.equal(e.actor_id,'demo-reviewer');assert.equal(e.item_version,s.fixture.items[0].version);assert.equal(e.approved_scope_hash,scopeHash(s.fixture.items[0]));assert.ok(Date.parse(e.decided_at));});
test('exact duplicate is idempotent; changed decision with same key conflicts',async()=>{const s=setup(),i=await input(s);await s.service.decide({},i);assert.equal((await s.service.decide({},i)).duplicate,true);await rejected(s.service.decide({},{...i,decision:'changes_requested'}),409);assert.equal((await s.audit.snapshot()).events.length,1);});
test('changed source revision rejects review without an audit event',async()=>{const s=setup(),i=await input(s);s.fixture.sheet_revision='mock-r2';await rejected(s.service.decide({},i),409);assert.equal((await s.audit.snapshot()).events.length,0);});
test('content change invalidates earlier approval and prevents replay resurrection',async()=>{const s=setup(),i=await input(s);await s.service.decide({},i);s.fixture.items[0].summary='changed scope';const v=await s.service.view({});assert.equal(v.items[0].decision,'pending');assert.equal(v.items[0].stale_decision,true);await rejected(s.service.decide({},i),409);});
test('revoked/expired recipients cannot submit',async()=>{const s=setup(),i=await input(s);s.revoke();await rejected(s.service.decide({},i),401);const t=setup();t.actor.expiresAt='2000-01-01T00:00:00Z';await rejected(t.service.view({}),401);});
test('simultaneous decisions use compare-and-swap to accept exactly one',async()=>{const s=setup(),i=await input(s);const results=await Promise.allSettled([s.service.decide({},i),s.service.decide({},{...i,idempotency_key:'request-key-0002'})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await s.audit.snapshot()).events.length,1);});
test('identity is revalidated after source/audit awaits',async()=>{const s=setup(),i=await input(s);let n=0;const svc=createReviewService({enabled:true,mode:'LOCAL_MOCK_ONLY',audit:s.audit,readCurrent:async()=>s.fixture,resolveActor:async()=>++n===1?s.actor:null});await rejected(svc.decide({},i),401);assert.equal((await s.audit.snapshot()).events.length,0);});
test('workbook canonical hash sorts keys, excludes hash, retains numeric types and normalizes UTC dates',()=>{const h=['content_hash','item_version','updated_at','empty','task_id'],c=['',1,'2026-10-04T18:00:00.000Z',null,'t1'],types={numeric:['item_version'],dates:['updated_at']};assert.equal(canonicalRow(h,c,types),'\u007b"empty":"","item_version":1,"task_id":"t1","updated_at":"2026-10-04T18:00:00Z"}');c[0]=rowHash(h,c,types);assert.equal(verifyRow(h,c,types),true);c[1]=2;assert.equal(verifyRow(h,c,types),false);assert.equal(WORKBOOK.mode,'read_only');});
test('formatted numeric values and timezone-ambiguous dates fail closed',()=>{assert.throws(()=>canonicalRow(['n'],['$5,000'],{numeric:['n']}));assert.throws(()=>canonicalRow(['at'],['10/4/2026'],{dates:['at']}));assert.throws(()=>canonicalRow(['a','a'],[1,2]));});
test('Sheets date serials normalize to the same UTC hash',()=>{assert.equal(rowHash(['at'],[25569],{dates:['at']}),rowHash(['at'],['1970-01-01T00:00:00Z'],{dates:['at']}));});
