import test from 'node:test';import assert from 'node:assert/strict';
import {createOwnerHistoryReader,projectDeidentifiedHistory,validateHistory} from '../tools/phillips-portal-prototype/historical-leads.mjs';
const batch={schema:'phillips.private-history/v1',mode:'OWNER_PRIVATE_SOURCE',tenant_id:'phillips',source_snapshot_ref:'synthetic-source',observed_at:'2026-10-04T20:00:00Z',coverage:{status:'PARTIAL',source_row_count:2,scope:'synthetic-only',reconciliation_ref:'synthetic-reconcile'},rows:[{private_record_id:'synthetic-id',campaign:'mva',source_row_ref:'synthetic-row',received_at:'2026-09-01T18:00:00Z',received_evidence_ref:'synthetic-received',sent_at:'2026-09-02T18:00:00Z',sent_kind:'SOURCE_REPORTED_SENT',sent_evidence_ref:'synthetic-sent',name:'SYNTHETIC PRIVATE NAME',phone:'synthetic-private-phone',email:'synthetic-private-email',medical_history:'synthetic-private-health',source_url:'synthetic-private-url',status:'Converted'}]};
test('deidentified historical view preserves received vs sent days, coverage and no inferred Signed',()=>{const x=projectDeidentifiedHistory(batch);assert.deepEqual(x.counts,{received:1,sent:1,verified_firm_receipts:0,signed:0});assert.equal(x.coverage.all_records_claim,false);assert.equal(x.rows[0].received_day,'2026-09-01');assert.equal(x.rows[0].sent_day,'2026-09-02');assert.equal(x.current_campaign_totals,false);assert.equal(x.outbound_enabled,false);for(const v of ['PRIVATE NAME','private-phone','private-email','private-health','private-url','synthetic-id','synthetic-row'])assert.ok(!JSON.stringify(x).includes(v));});
for(const [name,edit] of [['duplicate record',b=>b.rows.push(b.rows[0])],['missing sent proof',b=>delete b.rows[0].sent_evidence_ref],['complete claim without coverage',b=>b.coverage.status='COMPLETE_VERIFIED'],['Converted miscast Signed',b=>b.rows[0].signed_at='2026-09-03T18:00:00Z'],['wrong client',b=>b.tenant_id='other'],['unmatched ad match',b=>b.rows[0].ad_preview={kind:'MATCHED',ad_id:'different',asset_ref:'synthetic',evidence_ref:'synthetic'}]])test(`hold ${name}`,()=>{const b=structuredClone(batch);edit(b);assert.throws(()=>validateHistory(b));});
const actor={mode:'VERIFIED_OWNER_SESSION',tenant_id:'phillips',owner:true,subject:'synthetic-owner',scopes:['phillips:history:read'],expires_at:'2026-10-05T20:00:00Z'};
function reader(resolveOwner=async()=>actor,enabled=true){return createOwnerHistoryReader({enabled,resolveOwner,readPrivateSnapshot:async()=>batch,now:()=>new Date('2026-10-04T20:00:00Z')});}
test('disabled by default',async()=>await assert.rejects(createOwnerHistoryReader().view({}),{status:503}));
for(const [name,change] of [['mock identity',a=>a.mode='LOCAL_MOCK_ONLY'],['other tenant',a=>a.tenant_id='other'],['no owner',a=>a.owner=false],['wrong scope',a=>a.scopes=[]],['expired',a=>a.expires_at='2026-10-03T00:00:00Z']])test(`reject ${name}`,async()=>{const a=structuredClone(actor);change(a);await assert.rejects(reader(async()=>a).view({}),{status:401});});
test('owner session rechecked after private source read',async()=>{let n=0;await assert.rejects(reader(async()=>n++===0?actor:null).view({}),{status:401});});
test('authorized owner receives only deidentified read-only projection',async()=>assert.equal((await reader().view({})).rows.length,1));
