import test from 'node:test';import assert from 'node:assert/strict';
import { createReadOnlySheetAdapter, SCHEMA } from '../tools/phillips-portal-prototype/read-only-adapter.mjs';
import { rowHash } from '../tools/phillips-portal-prototype/sheet-contract.mjs';
const types=h=>({numeric:h.filter(k=>/^(item_version|target_item_version|budget_usd|duration_days|meta_website_usd|google_search_usd|estimated_cost)$/.test(k)),dates:h.filter(k=>/_at$/.test(k))});
function row(tab,obj){const h=SCHEMA[tab],v=h.map(k=>obj[k]??(k==='item_version'?1:''));v[h.indexOf('content_hash')]=rowHash(h,v,types(h));return v;}
function setup(){const state=row('CurrentState',{state_id:'s1',tenant_id:'phillips',workstream_id:'campaign',status:'planned_not_live',safe_summary:'Planned work remains held.',observed_at:46299.7621875,budget_usd:5000,duration_days:14,meta_website_usd:3000,google_search_usd:2000,evidence_url:'https://private.example/evidence'});
 const task=row('Tasks',{task_id:'t1',tenant_id:'phillips',state_id:'s1',title:'Review scope',assignee_id:'owner-A',status:'pending_details',approval_request_id:'r1',updated_at:46299.7621875,evidence_url:'https://private.example/task'});
 const request=row('ApprovalRequests',{request_id:'r1',tenant_id:'phillips',task_id:'t1',action_type:'asset_review',exact_scope:'Still pending details',approver_id:'owner-A',status:'pending_details',created_at:46299.7621875,target_item_id:'t1',target_item_version:1,target_content_hash:task[SCHEMA.Tasks.indexOf('content_hash')]});
 const tabs={CurrentState:{values:[SCHEMA.CurrentState,state]},Tasks:{values:[SCHEMA.Tasks,task]},ApprovalRequests:{values:[SCHEMA.ApprovalRequests,request]},ApprovalLog:{values:[SCHEMA.ApprovalLog]}};
 const actor={serverVerified:true,access:'OWNER_READ_ONLY',subject:'owner-A',tenantId:'phillips',stateIds:['s1'],taskIds:['t1'],expiresAt:'2099-01-01T00:00:00Z'};let calls=0;
 const adapter=createReadOnlySheetAdapter({enabled:true,readRange:async({sheet_name})=>{calls++;return tabs[sheet_name];},resolveActor:async()=>actor});return {tabs,actor,adapter,calls:()=>calls};}
const rejected=(p,status)=>assert.rejects(p,e=>e.status===status);
test('read-only adapter defaults disabled with no source calls',async()=>{let called=false;await rejected(createReadOnlySheetAdapter({readRange:()=>called=true}).read({}),503);assert.equal(called,false);});
test('real-schema projection preserves source observation, typed plan and pending requests without enabling decisions',async()=>{const s=setup(),p=await s.adapter.read({});assert.equal(s.calls(),4);assert.equal(p.current_state[0].observed_at,'2026-10-04T18:17:33Z');assert.equal(p.plan.total_usd,5000);assert.equal(p.plan.source_updated_at,null);assert.equal(p.tasks.length,1);assert.equal(p.approval_requests[0].status,'pending_details');assert.equal(p.approval_requests[0].decisions_enabled,false);assert.equal(p.execution_authorized,false);assert.doesNotMatch(JSON.stringify(p),/private\.example|evidence_url|spreadsheet_id/);assert.equal(p.review_history.length,0);});
test('blank task assignees and approvers are not inferred',async()=>{const s=setup();s.tabs.Tasks.values[1]=row('Tasks',{task_id:'t1',tenant_id:'phillips',state_id:'s1',title:'Review scope',status:'pending_details'});s.tabs.ApprovalRequests.values=[SCHEMA.ApprovalRequests];const p=await s.adapter.read({});assert.equal(p.tasks.length,0);assert.equal(p.approval_requests.length,0);});
test('invalid content hash holds the entire projection',async()=>{const s=setup();s.tabs.CurrentState.values[1][SCHEMA.CurrentState.indexOf('safe_summary')]='changed';await rejected(s.adapter.read({}),503);});
test('changed headers require mapper review',async()=>{const s=setup();s.tabs.Tasks.values[0]=[...SCHEMA.Tasks,'extra'];await rejected(s.adapter.read({}),503);});
test('request target mismatch holds projection even if request hash is valid',async()=>{const s=setup();const obj=Object.fromEntries(SCHEMA.ApprovalRequests.map((h,i)=>[h,s.tabs.ApprovalRequests.values[1][i]]));obj.target_item_version=2;s.tabs.ApprovalRequests.values[1]=row('ApprovalRequests',obj);await rejected(s.adapter.read({}),503);});
test('wrong tenant and unverified actor fail before workbook reads',async()=>{const s=setup();s.actor.tenantId='other';await rejected(s.adapter.read({}),401);assert.equal(s.calls(),0);const t=setup();t.actor.serverVerified=false;await rejected(t.adapter.read({}),401);assert.equal(t.calls(),0);});
test('recipient scope is rechecked after reads',async()=>{const s=setup();let calls=0;const adapter=createReadOnlySheetAdapter({enabled:true,readRange:async({sheet_name})=>s.tabs[sheet_name],resolveActor:async()=>++calls===1?s.actor:{...s.actor,stateIds:[]}});await rejected(adapter.read({}),401);});
test('an approved Sheet status is informational and cannot create review history',async()=>{const s=setup();const obj=Object.fromEntries(SCHEMA.ApprovalRequests.map((h,i)=>[h,s.tabs.ApprovalRequests.values[1][i]]));obj.status='approved';s.tabs.ApprovalRequests.values[1]=row('ApprovalRequests',obj);const p=await s.adapter.read({});assert.equal(p.decisions_enabled,false);assert.deepEqual(p.review_history,[]);assert.equal(s.adapter.decide,undefined);});
