window.DOMAIN_CONFIG={
  "DOMAIN_ID": "RI",
  "DOMAIN_HOST": "researchinvestigation.com",
  "BRAND_NAME": "Research Investigation",
  "VERTICAL": "leadgen",
  "PAGE_VERSION": "20260919-1",
  "PAGE_SLUG": "index",
  "CAMPAIGN_ID": "RI_V1",
  "LEAD_SOURCE": "site_form",
  "ENDPOINT": "https://hook.us2.make.com/3simdd4xno0o9lh9jlsjdkc64570s3c4",
  "PHONE": "(619) 736-0356",
  "SUPPORT_EMAIL": "hello@researchinvestigation.com",
  "VOICE_ENABLED": false,
  "SMS_ENABLED": false,
  "GTM_ID": "GTM-N3B29SZD",
  "GA4_MEASUREMENT_ID": "G-RGJRR0CW8T",
  "META_PIXEL_ID": "",
  "CONSENT_VERSION": "RI_TCPA_2026-09-18_V1",
  "GTM_SERVER_CONTAINER_ID": "GTM-TRK6B33C",
  "GTM_SERVER_URL": "",
  "TIKTOK_PIXEL_ID": "",
  "GOOGLE_ADS_TAG_ID": "",
  "GOOGLE_ADS_CONVERSION_LABEL": "",
  "DOMAIN_ROLE": "acquisition_surface",
  "FIRM_VISIBLE": false,
  "ENVELOPE_DOMAIN": "",
  "RENDER_SERVICE": "ri-site",
  "THANK_YOU_URL": "/thank-you.html"
};
