"""Package a generic, read-only public demonstration. Does not publish or share it."""
from pathlib import Path
import base64
root=Path(__file__).resolve().parents[2]
a=root/'lfma/portal/prototypes/phillips-current'
css='\n'.join((a/x).read_text() for x in ['portal.css','prototype.css'])
logo=base64.b64encode((a/'ma-logo.png').read_bytes()).decode()
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Client Perspective · Marketing Apes</title><style>CSS</style></head><body>
<header class="top"><div class="wrap"><div class="brand"><img src="data:image/png;base64,LOGO" alt="Marketing Apes" width="48" height="48"><div class="sys">Client Perspective<small>Marketing Apes · Your campaign, connected</small></div></div><span class="draft-pill">Demo</span></div></header>
<main class="wrap"><section class="hero"><div class="eyebrow">YOUR CAMPAIGN. THE COMPLETE PICTURE.</div><h1>From first click<br>to verified outcome.</h1><p class="intro">See what your marketing brings in, how each lead is worked, and how your firm’s feedback helps us improve.</p><p class="notice">Read-only demonstration · No live client data</p><p id="source">Explore the system below. Results appear when verified sources are connected.</p></section>
<nav class="tabs" aria-label="Portal sections"><button data-tab="overview" aria-selected="true">Overview</button><button data-tab="campaigns" aria-selected="false">Campaigns</button><button data-tab="leads" aria-selected="false">Lead journey</button><button data-tab="feedback" aria-selected="false">Firm feedback</button><button data-tab="optimization" aria-selected="false">Optimization</button><button data-tab="tasks" aria-selected="false">My tasks</button></nav>
<section id="overview" class="panel"><div class="section-head"><div><div class="eyebrow">ONE SHARED PICTURE</div><h2>Know where every step stands.</h2></div><span class="status-pill">Demo · Not connected</span></div><div class="metrics"><article><h3>Campaign investment</h3><strong>Awaiting data</strong><p>Actual spend and its reporting period.</p></article><article><h3>Leads received</h3><strong>Awaiting data</strong><p>Verified leads, with source coverage visible.</p></article><article><h3>Verified outcomes</h3><strong>Awaiting data</strong><p>Signed means an executed retainer is evidenced.</p></article><article><h3>Cost per outcome</h3><strong>Awaiting data</strong><p>Comparable spend and verified outcomes.</p></article></div><div class="journey"><div class="eyebrow">HOW YOUR SYSTEM WORKS</div><h2>Connected work. Accountable outcomes.</h2><div class="flow"><article><span>01</span><h3>Campaign</h3><p>Creative, audience and investment</p><strong>Plan and measure</strong></article><article><span>02</span><h3>Lead</h3><p>Consent and source capture</p><strong>Record the origin</strong></article><article><span>03</span><h3>Intake work</h3><p>Contact, qualify and transfer</p><strong>Track the work</strong></article><article><span>04</span><h3>Firm feedback</h3><p>Disposition from your team</p><strong>Close the loop</strong></article><article><span>05</span><h3>Verified outcome</h3><p>Executed-retainer evidence</p><strong>Verify the result</strong></article><article><span>06</span><h3>Optimization</h3><p>Improve from trusted results</p><strong>Review each change</strong></article></div></div></section>
<section id="campaigns" class="panel" hidden><h2>A complete campaign breakdown</h2><p>Compare the plan with actual delivery, using clear reporting periods and source freshness.</p><div class="cards"><article><h3>Plan and creative</h3><p>Review each campaign’s objective, channel, landing experience and approved creative version.</p><strong>No campaign connected</strong></article><article><h3>Investment and performance</h3><p>See verified spend, lead counts and outcome costs. Missing coverage stays visible.</p><strong>No performance data connected</strong></article><article><h3>Freshness and evidence</h3><p>Know when the source was updated and which results remain unresolved.</p><strong>No source update verified</strong></article></div></section>
<section id="leads" class="panel" hidden><h2>What happens after a lead arrives?</h2><p>Follow the work from receipt through contact, transfer and firm follow-up. Each stage stays distinct, so an attempted call never looks like a completed transfer.</p><div class="cards"><article><h3>Received and contacted</h3><p>Verify receipt, consent, source and the result of contact attempts.</p><strong>Awaiting verified records</strong></article><article><h3>Qualified and transferred</h3><p>See whether intake progressed and the receiving team acknowledged the transfer.</p><strong>Awaiting verified records</strong></article><article><h3>Firm follow-up</h3><p>Track disposition and next steps in a recipient-authorized view. This public demo contains no individual lead records.</p><strong>Protected access required</strong></article></div></section>
<section id="feedback" class="panel" hidden><h2>Your firm’s feedback closes the loop.</h2><p>Marketing needs to know what happened after intake. Unmatched or uncertain feedback stays unresolved until evidence supports a match.</p><div class="cards"><article><h3>Disposition</h3><p>Capture accepted, declined and follow-up stages without collapsing them into a signed case.</p></article><article><h3>Verified outcome</h3><p>A converted lead or a sent retainer is not counted as Signed without executed-retainer evidence.</p></article><article><h3>Access and privacy</h3><p>Each recipient sees only their authorized firm, work and records. No raw lead data is exposed in this demo.</p></article></div></section>
<section id="optimization" class="panel" hidden><h2>Improve from evidence.</h2><p>Connect marketing performance with intake and firm outcomes before recommending a change.</p><div class="cards"><article><h3>Find the opportunity</h3><p>Compare verified results by campaign and identify gaps in coverage or lead handling.</p></article><article><h3>Review the proposed change</h3><p>Make the exact scope, expected cost and supporting evidence clear to the responsible approver.</p></article><article><h3>Keep changes accountable</h3><p>Record the reviewed version and decision. Publishing and spending require separate authorization.</p></article></div><p class="notice">No optimization changes are performed in this demonstration.</p></section>
<section id="tasks" class="panel" hidden><h2>Your next actions, in one place.</h2><p>In a connected private portal, tasks and review requests are scoped to your verified identity. No recipient is signed in to this public demonstration.</p><div class="cards"><article><h3>Assigned work</h3><p>See the next action, owner, due date and acceptance criteria.</p><strong>Sign-in required in a connected portal</strong></article><article><h3>Review requests</h3><p>Review an exact version and scope before recording a decision.</p><strong>No actions available in this demo</strong></article><article><h3>Decision history</h3><p>Keep actor, time, version and evidence together. Changed scope requires a fresh review.</p><strong>No decision history connected</strong></article></div></section>
<footer><p>Marketing Apes · Client Perspective · Read-only demonstration</p></footer></main><script>document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b===button)));document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==button.dataset.tab);}));</script></body></html>'''
html=html.replace('CSS',css).replace('LOGO',logo)
(a/'client-perspective-demo.html').write_text(html)
print(a/'client-perspective-demo.html')
