window.DOMAIN_CONFIG={
  "DOMAIN_ID": "DENTAL",
  "DOMAIN_HOST": "dentalmarketingapes.com",
  "BRAND_NAME": "Dental Marketing Apes",
  "VERTICAL": "b2b-agency",
  "PAGE_VERSION": "20260919-1",
  "PAGE_SLUG": "index",
  "CAMPAIGN_ID": "DENTAL_V1",
  "LEAD_SOURCE": "site_form",
  "ENDPOINT": "",
  "PHONE": "(619) 736-0356",
  "SUPPORT_EMAIL": "hello@dentalmarketingapes.com",
  "VOICE_ENABLED": false,
  "SMS_ENABLED": false,
  "GTM_ID": "GTM-MDHGKQV",
  "GA4_MEASUREMENT_ID": "",
  "META_PIXEL_ID": "",
  "CONSENT_VERSION": "DENTAL_TCPA_2026-09-18_V1",
  "GTM_SERVER_CONTAINER_ID": "GTM-P955GDZ5",
  "GTM_SERVER_URL": "https://server-side-tagging-nn3socwquq-uc.a.run.app",
  "TIKTOK_PIXEL_ID": "",
  "GOOGLE_ADS_TAG_ID": "",
  "GOOGLE_ADS_CONVERSION_LABEL": "",
  "DOMAIN_ROLE": "acquisition_surface",
  "FIRM_VISIBLE": false,
  "ENVELOPE_DOMAIN": "",
  "RENDER_SERVICE": "dental-site",
  "THANK_YOU_URL": "/thank-you.html"
};
