import fs from 'node:fs';
import {brands,topics,VERSION} from './catalog.mjs';
const source='campaign-system';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
for(const b of brands){
 const dir=`${b.id}/campaigns`;fs.mkdirSync(dir,{recursive:true});
 for(const file of ['catalog.mjs','model.mjs','app.mjs','style.css'])fs.copyFileSync(`${source}/${file}`,`${dir}/${file}`);
 fs.writeFileSync(`${dir}/index.html`,fs.readFileSync(`${source}/studio.html`,'utf8').replaceAll('__BRAND__',esc(b.name)).replaceAll('__ID__',b.id));
 for(const t of topics){
  fs.mkdirSync(`${dir}/${t.id}`,{recursive:true});
  fs.writeFileSync(`${dir}/${t.id}/index.html`,`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="referrer" content="no-referrer"><title>${esc(t.name)} campaign · ${esc(b.name)}</title><meta name="description" content="Preview a ${esc(t.name)} campaign, review the page approach and configure a two-week sprint."><link rel="stylesheet" href="../style.css"></head><body style="--accent:${b.color}"><header><a href="/">${esc(b.name)}</a><a href="../">Campaign studio</a></header><main><div class="hero"><p class="eyebrow">${esc(t.category)} · Campaign preview</p><h1>${esc(t.name)}.<br>A clear next step.</h1><p class="notice">Template preview for campaign discussion. This page does not collect legal inquiries or confirm that a firm is accepting claims.</p><p>Build a focused campaign around ${esc(t.name.toLowerCase())}, with a clear audience, a dedicated page and a verified inquiry destination.</p><a class="cta primary" data-cta-id="configure-campaign" href="../?brand=${b.id}&topic=${t.id}">Customize this campaign</a></div><div class="topic-grid"><section class="panel"><h2>What this campaign needs</h2><p>${esc(t.review)}</p><p>${t.id==='mva'?'Start with a proposed 50-mile radius around the firm’s office. Confirm the address, service area and permitted jurisdictions before targeting.':'Confirm the approved states, acceptance criteria and responsible firm before accepting inquiries.'}</p></section><section class="panel"><h2>Two page approaches</h2><p><strong>Direct response:</strong> Explain the topic, the next step and how an inquiry is handled.</p><p><strong>Education first:</strong> Provide reviewed topic information and answers before inviting a private inquiry.</p><p>Channel selection and any retargeting depend on campaign eligibility and approved data use.</p></section></div><section class="panel"><h2>Request → Review → Launch → Updates</h2><p>Agree scope and funding, review the page and disclosures, verify a complete inquiry handoff, then run a 14-day sprint. Review spend and returned outcomes daily.</p><p>Payment begins preparation. It does not replace launch review or guarantee a number of leads or signed cases.</p>${t.source?`<p>Research starting point: <a href="${t.source}" rel="noreferrer">JPML September 2026 docket report</a>, MDL ${t.mdl}. A docket listing does not establish eligibility, liability, a filing deadline or current intake availability.</p>`:''}</section></main><footer>Campaign preview · ${esc(b.name)} · No attorney-client relationship is created. This template requires campaign-specific review before consumer publication.</footer></body></html>`);
 }
 fs.writeFileSync(`${dir}/release.json`,JSON.stringify({version:VERSION,brand:b.id,topics:topics.length,status:'demo',leadCollection:false,indexing:false},null,2)+'\n');
 const f=`${b.id}/domain.json`;if(fs.existsSync(f)){const d=JSON.parse(fs.readFileSync(f));d.campaign_studio={path:'/campaigns/',version:VERSION,source:'campaign-system/',status:'demo',topic_count:topics.length,lead_collection:false,organic_publication:'review_required'};fs.writeFileSync(f,JSON.stringify(d,null,2)+'\n');}
}
console.log(`Built ${brands.length} studios and ${brands.length*topics.length} topic previews.`);
