// Browser-only port of reviewed DraftStore; validation/snapshots unchanged. Web Crypto replaces Node crypto.
import {campaignOffer} from './campaign-offer.js';
import {buyerCatalog,validSpecificClaim} from './campaign-scope.js';
const randomUUID=()=>crypto.randomUUID();
const digest=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(byte=>byte.toString(16).padStart(2,'0')).join('');
export const fields = ['firm','claim','geography','intakePreference','claimDescription','firmCriteria'];
const required=v=>['claim',...(v.claim==='other-specific'?['claimDescription']:[]),'firm','geography','intakePreference'];
export const geographies = ['California','Arizona','California and Arizona'];
export const preferences = ['Firm intake team','Approved intake partner','Discuss with Kyle'];
export class DraftError extends Error { constructor(code,status=400){super(code);this.code=code;this.status=status;} }
const fail=(code,status)=>{throw new DraftError(code,status);};
const exact=(obj,keys)=>{if(!obj||typeof obj!=='object'||Array.isArray(obj)||Object.keys(obj).some(k=>!keys.includes(k)))fail('invalid_shape');};
export class DraftStore {
 constructor(catalog,{maxSessions=5,ttlMs=30*60*1000,maxChanges=60,clock=Date.now}={}) {this.catalog=buyerCatalog(catalog);this.sessions=new Map();this.maxSessions=maxSessions;this.ttlMs=ttlMs;this.maxChanges=maxChanges;this.clock=clock;}
 create() {for(const [token,s] of this.sessions)if(s.expiresAt<=this.clock())this.sessions.delete(token);while(this.sessions.size>=50){const old=[...this.sessions].find(([,v])=>v.status==='cancelled');if(!old)break;this.sessions.delete(old[0]);}if([...this.sessions.values()].filter(v=>v.status!=='cancelled').length>=this.maxSessions)fail('preview_capacity',429);const token=crypto.randomUUID()+crypto.randomUUID(),s={id:randomUUID(),seq:0,values:{},status:'draft',expiresAt:this.clock()+this.ttlMs,events:[],requests:new Map()};this.sessions.set(token,s);this.emit(s,'created');return {token,...this.read(token)};}
 session(token){const s=this.sessions.get(token);if(!s||s.expiresAt<=this.clock()){this.sessions.delete(token);fail('session_unavailable',401);}return s;}
 snapshot(s){const c=this.catalog.find(c=>c.id===s.values.claim),firm=s.values.firm||'Your firm',geo=s.values.geography||'Geography to confirm',pref=s.values.intakePreference||'Intake preference to confirm',claimLabel=s.values.claim==='other-specific'?(s.values.claimDescription||'Specific claim description pending'):(c?.label||'One claim type to confirm');return {schema:'lfma.campaign_draft.v1',id:s.id,revision:s.seq,status:s.status,values:{...s.values},lastConfirmedField:s.lastConfirmedField||null,confirmedFields:Object.keys(s.values),requiredFields:required(s.values),reviewVersion:s.reviewVersion?structuredClone(s.reviewVersion):null,expiresAt:s.expiresAt,artifacts:{firm,initials:firm.split(/\s+/).map(w=>w[0]).join('').slice(0,2).toUpperCase(),claim:claimLabel,ad:{source:'Facebook ad draft · BTL matching service',headline:`Explore a fictional ${claimLabel} inquiry`,copy:`BTL matching-service draft for ${geo}. Sample receiving firm: ${firm}. No firm endorsement, eligibility decision or active ad.`},landing:{headline:`${firm}: campaign review preview`,copy:`Fictional ${c?.scenarioName||'sample scenario'} · ${claimLabel} · ${geo}. BTL is the matching service; ${firm} is the proposed receiving firm. No actual claimant information.`},criteriaStatus:'awaiting_firm_approved_criteria',firmSuppliedDraftCriteria:s.values.firmCriteria||null,claimReviewRequired:true,questions:c?.questions.map(q=>({label:q.label,options:[...q.options]}))||[],handoff:{destination:pref,summary:`Fictional Alex · ${claimLabel} · ${geo} → ${pref}. Ask permission before any live handoff.`,attempted:false,connected:false,phoneReceipts:false}},offer:{...campaignOffer},legalCriteriaApproved:false,adActivated:false,orderAccepted:false,paymentStatus:'unverified'};}
 emit(s,type){s.seq++;s.events.push({schema:'lfma.campaign_event.v1',sessionId:s.id,sequence:s.seq,type,status:s.status,snapshot:this.snapshot(s)});}
 read(token,after=0){const s=this.session(token);if(!Number.isInteger(after)||after<0||after>s.seq)fail('invalid_cursor');return {snapshot:this.snapshot(s),events:structuredClone(s.events.filter(e=>e.sequence>after))};}
 async apply(token,op){exact(op,['eventId','expectedRevision','action','field','value','buyerConfirmed']);if(typeof op.eventId!=='string'||! /^[a-zA-Z0-9:_-]{1,150}$/.test(op.eventId))fail('invalid_event_id');const s=this.session(token),fingerprint=JSON.stringify(['action','expectedRevision','field','value','buyerConfirmed'].map(k=>[k,op[k]]));const existing=s.requests.get(op.eventId);if(existing){if(existing.fingerprint!==fingerprint)fail('idempotency_conflict',409);return structuredClone(existing.result);}
 if(s.status==='cancelled')fail('session_cancelled',409);if(op.action!=='cancel'&&op.expectedRevision!==s.seq)fail('revision_conflict',409);if(!['update','review','cancel'].includes(op.action))fail('invalid_action');if(op.action!=='cancel'&&s.seq>this.maxChanges)fail('session_change_limit',429);
 if(op.action==='cancel'){if('field' in op||'value' in op)fail('invalid_shape');s.status='cancelled';s.values={};s.reviewVersion=null;s.lastConfirmedField=null;s.events=[];s.requests.clear();}
 else {if(op.buyerConfirmed!==true)fail('buyer_confirmation_required');if(op.action==='review'){if('field' in op||'value' in op)fail('invalid_shape');if(!required(s.values).every(f=>s.values[f]))fail('brief_incomplete');s.status='review_ready';const derived=this.snapshot(s);s.reviewVersion={revision:s.seq+1,values:structuredClone(s.values),artifacts:structuredClone(derived.artifacts),offer:structuredClone(derived.offer),derivedHash:await digest(JSON.stringify({values:Object.fromEntries(Object.entries(s.values).sort(([a],[b])=>a<b?-1:a>b?1:0)),artifacts:derived.artifacts,offer:derived.offer})),confirmedAt:this.clock(),superseded:false};}else {if(!fields.includes(op.field)||typeof op.value!=='string')fail('invalid_field');const value=op.field==='firmCriteria'?op.value:op.value.trim();if(op.field==='claimDescription'){if(s.values.claim!=='other-specific'||!validSpecificClaim(value))fail('specific_claim_review_required');}else if(op.field==='firmCriteria'){if(value.length>350||/[<>\x00-\x08\x0b\x0c\x0e-\x1f]/.test(value))fail('invalid_draft_criteria');}else if(op.field==='firm'){if(!value||value.length>70||/[<>\x00-\x1f]/.test(value))fail('invalid_firm');}else if(op.field==='claim'){if(!this.catalog.some(c=>c.id===value))fail('unknown_claim');}else if(op.field==='geography'){if(!geographies.includes(value))fail('unsupported_geography');}else if(!preferences.includes(value))fail('unsupported_intake_preference');if(op.field==='claim'&&s.values.claim!==value){delete s.values.claimDescription;delete s.values.firmCriteria;}s.values[op.field]=value;s.lastConfirmedField=op.field;s.status='draft';if(s.reviewVersion)s.reviewVersion.superseded=true;}}
 s.expiresAt=this.clock()+this.ttlMs;this.emit(s,op.action==='update'?'field_confirmed':op.action==='review'?'review_ready':'cancelled');const result=this.read(token,s.seq-1);s.requests.set(op.eventId,{fingerprint,result:structuredClone(result)});return result;
 }
}
