import {browserApi,clearBrowserDrafts} from './browser-api.js';
import {campaignOffer,offerMoney} from './campaign-offer.js';
import {renderDraft} from './draft-renderer.js';
const key='lfma-browser-preview-session-v1',el=id=>document.getElementById(id);
sessionStorage.removeItem(key); // Discard legacy capabilities copied by opener/duplicate tabs.
let catalog=[],initializing=null;
let token=null,snapshot=null,generation=0,pollTimer=null,busy=false,inFlight=null,finishFlight=null;
function status(text){el('draft-status').textContent=text;el('entry-status').textContent=/unavailable|disconnected|expired/i.test(text)?text:'';const unavailable=/unavailable|disconnected/i.test(text);el('builder-availability').hidden=!unavailable;el('builder-unavailable-message').textContent=unavailable?'Tab draft unavailable. The story and offer stay readable. Retry the tab draft.':'';}
async function api(path,method='GET',data,credential=token){return browserApi(path,method,data,credential);}
function accept(value,epoch){if(epoch!==generation)return;const next=value.snapshot;if(snapshot&&next.id===snapshot.id&&next.revision<snapshot.revision)return;if(snapshot&&next.id!==snapshot.id)throw new Error('Wrong-session event rejected');const changed=!snapshot||next.revision!==snapshot.revision;if(snapshot&&changed&&next.status==='draft')el('brief-confirmed').checked=false;snapshot=next;document.dispatchEvent(new CustomEvent('draft-changed',{detail:structuredClone(snapshot)}));if(changed)renderDraft(el('draft-canvas'),snapshot);el('draft-status').dataset.sessionId=snapshot.id;el('draft-status').dataset.revision=snapshot.revision;const descriptionOption=el('draft-field').querySelector('[value=claimDescription]');descriptionOption.hidden=snapshot.values.claim!=='other-specific';descriptionOption.disabled=descriptionOption.hidden;el('draft-status').dataset.phase=snapshot.status;status(snapshot.status==='review_ready'?'Your draft is ready for review. Nothing has launched.':snapshot.status==='cancelled'?'Draft cancelled. Your business answers have been cleared.':'Your draft is taking shape · browser-only demonstration.');el('start-builder').disabled=false;el('test-ai-step').hidden=!snapshot.values.claim;if(changed)el('firm-criteria').value=snapshot.values.firmCriteria||'';el('review-controls').hidden=!snapshot.requiredFields.every(f=>snapshot.values[f]);if(changed)el('draft-form').hidden=snapshot.requiredFields.every(f=>snapshot.values[f]);if(changed&&snapshot.status!=='cancelled'){const nextField=snapshot.requiredFields.find(f=>!snapshot.values[f]);if(nextField)el('draft-field').value=nextField;fieldControl();}el('review-draft').disabled=busy||snapshot.status==='cancelled'||!snapshot.requiredFields.every(f=>snapshot.values[f]);el('confirm-field').disabled=busy||snapshot.status==='cancelled';el('cancel-draft').disabled=busy||snapshot.status==='cancelled';const log=el('draft-log');for(const event of value.events){if(event.sessionId!==snapshot.id||event.sequence>snapshot.revision)continue;const row=document.createElement('li');row.textContent=`${event.sequence} · ${event.type.replaceAll('_',' ')} · draft only`;if(!log.querySelector(`[data-sequence="${event.sequence}"]`)){row.dataset.sequence=event.sequence;log.append(row);}}if(snapshot.status==='cancelled'){log.replaceChildren();clearTimeout(pollTimer);sessionStorage.removeItem(key);token=null;el('draft-field').value='firm';fieldControl();el('buyer-confirmed').checked=false;el('brief-confirmed').checked=false;}}
async function refresh(){if(!token)return;const epoch=generation;try{accept(await api('events?after='+(snapshot?.revision||0)),epoch);}catch(e){if(epoch===generation){if(e.message==='session_unavailable')expire();else status('Preview disconnected. Reconnect to read your draft.');}}}
function expire(){el('builder-entry').hidden=true;el('draft-workspace').hidden=false;clearTimeout(pollTimer);document.dispatchEvent(new CustomEvent('draft-expired'));token=null;snapshot=null;el('draft-canvas').replaceChildren();el('draft-log').replaceChildren();el('cancel-draft').disabled=true;el('confirm-field').disabled=true;el('review-draft').disabled=true;el('draft-form').hidden=true;el('review-controls').hidden=true;el('start-builder').disabled=true;el('reconnect-draft').disabled=true;status('Your draft expired after inactivity. Answers were cleared. Choose Start fresh to create a new draft.');}
function poll(){clearTimeout(pollTimer);pollTimer=setTimeout(async()=>{await refresh();if(token)poll();},800);}
async function connect(){const epoch=++generation;clearTimeout(pollTimer);snapshot=null;el('draft-log').replaceChildren();status('Preparing this tab’s browser-only draft…');try {let value;if(token){try{value=await api('events');}catch(e){if(e.message==='session_unavailable'){expire();return;}throw e;}}if(!token){value=await api('session','POST',{},null);token=value.token;}accept(value,epoch);el('reconnect-draft').disabled=false;fieldControl();el('buyer-confirmed').checked=false;el('brief-confirmed').checked=false;if(token)poll();}catch(e){el('start-builder').disabled=false;status('Draft unavailable: '+e.message+'. Try Start fresh; live voice remains disabled.');}}
async function command(action,field,value){if(busy||!token||(action!=='cancel'&&!snapshot))return;busy=true;inFlight=new Promise(r=>finishFlight=r);el('confirm-field').disabled=true;el('review-draft').disabled=true;const epoch=generation;try {const result=await api('command','POST',{eventId:crypto.randomUUID(),expectedRevision:snapshot?.revision||0,action,buyerConfirmed:true,...(action==='update'?{field,value}:{})});accept(result,epoch);if(action==='update')(el('draft-form').hidden?(el('offer-review')||el('review-draft')):(el('claim-search')||el('draft-value'))).focus();if(action==='review'){const heading=el('draft-canvas').querySelector('h2,h3');if(heading){heading.tabIndex=-1;heading.focus();}}}catch(e){const messages={invalid_firm:'Use a firm name of 1–70 characters without markup or line breaks.',specific_claim_review_required:'Enter a specific claim for review. Vehicle accidents and generic personal injury are outside this offer.',invalid_draft_criteria:'Use up to 350 characters of business requirements without markup.',unsupported_geography:'Choose California, Arizona, or both.',unknown_claim:'Choose a listed claim type.',unsupported_intake_preference:'Choose a listed intake preference.',brief_incomplete:'Complete the required business answers first.',buyer_confirmation_required:'Confirm the business answer before continuing.'};if(e.message==='session_unavailable')expire();else status(messages[e.message]||'Update not applied. Reconnect to read your draft, then confirm again.');}finally{busy=false;finishFlight?.();inFlight=null;finishFlight=null;if(snapshot&&epoch===generation){el('confirm-field').disabled=snapshot.status==='cancelled';el('review-draft').disabled=snapshot.status==='cancelled'||!snapshot.requiredFields.every(f=>snapshot.values[f]);el('cancel-draft').disabled=snapshot.status==='cancelled';}}}
const aliases={'sexual-abuse':'sex abuse sexual abuse','workers':'workers comp workers compensation','lemon-law':'lemon law'};const normalize=text=>text.toLowerCase().replace(/[’'−-]/g,' ').replace(/\s+/g,' ').trim();
function fieldControl(){const box=el('field-control');box.replaceChildren();const field=el('draft-field').value,label=document.createElement('label');label.textContent=({firm:'What should we call your firm?',claim:'What kind of cases do you want?',geography:'Where should the campaign run?',intakePreference:'Who should receive inquiries?',claimDescription:'Which specific claim should Kyle review?'})[field];label.htmlFor='draft-value';box.append(label);if(field==='claim'){const value=document.createElement('input');value.id='draft-value';value.type='hidden';value.value=snapshot?.values.claim||'';const search=document.createElement('input');search.type='search';search.id='claim-search';search.placeholder='Talc, sex abuse, workers’ comp, lemon law…';search.setAttribute('aria-label','Search a claim type');label.htmlFor=search.id;const options=document.createElement('div');options.className='claim-options';const show=()=>{options.replaceChildren();const matches=search.value?catalog.filter(c=>normalize([c.id,c.label,c.category,aliases[c.id]||''].join(' ')).includes(normalize(search.value))).sort((a,b)=>Number(normalize(aliases[b.id]||'').includes(normalize(search.value)))-Number(normalize(aliases[a.id]||'').includes(normalize(search.value)))).slice(0,3):['talc','sexual-abuse','workers','lemon-law'].map(id=>catalog.find(c=>c.id===id)).filter(Boolean);const noMatch=matches.length===0;if(search.value&&!matches.some(c=>c.id==='other-specific')){const other=catalog.find(c=>c.id==='other-specific');if(other)matches.push(other);}for(const c of matches){const b=document.createElement('button');b.type='button';b.className='claim-option';b.dataset.claim=c.id;b.textContent=c.label;b.setAttribute('aria-pressed',String(value.value===c.id));b.onclick=()=>{value.value=c.id;options.querySelectorAll('button').forEach(option=>option.setAttribute('aria-pressed',String(option.dataset.claim===c.id)));};options.append(b);}if(noMatch){const p=document.createElement('p');p.textContent='No catalog match. Try another term or discuss the scope with Kyle.';options.append(p);}};search.oninput=show;box.append(value,search,options);show();return;}const choices=field==='geography'?['California','Arizona','California and Arizona']:field==='intakePreference'?['Firm intake team','Approved intake partner','Discuss with Kyle']:null;const input=document.createElement(choices?'select':'input');input.id='draft-value';input.name='draft-value';input.required=true;input.maxLength=70;if(choices)for(const text of choices){const o=document.createElement('option');o.value=text;o.textContent=text;input.append(o);}if(snapshot?.values[field])input.value=snapshot.values[field];box.append(input);}
document.querySelectorAll('[data-offer]').forEach(node=>node.textContent=offerMoney(campaignOffer[node.dataset.offer]));
async function initialize(){if(initializing)return initializing;initializing=(async()=>{el('retry-builder').disabled=true;el('start-builder').disabled=true;status('Preparing this tab’s browser-only draft…');try{const value=await api('catalog','GET',undefined,null);if(!Array.isArray(value.catalog)||!value.catalog.length||value.catalog.length>100||!value.catalog.every(c=>c&&typeof c.id==='string'&&typeof c.label==='string'&&Array.isArray(c.questions)))throw new Error('catalog_invalid');catalog=value.catalog;await connect();}catch{el('start-builder').disabled=false;status('Draft unavailable. Retry the tab draft to build your campaign.');}finally{el('retry-builder').disabled=false;initializing=null;}})();return initializing;}
el('retry-builder').onclick=()=>{if(!busy)initialize();};
el('draft-field').onchange=()=>{el('draft-form').hidden=false;el('buyer-confirmed').checked=false;fieldControl();el('edit-fields').open=false;};fieldControl();el('start-builder').onclick=async()=>{if(!token||!snapshot){if(catalog.length)await connect();else await initialize();}if(!token||!snapshot)return;el('builder-entry').hidden=true;el('draft-workspace').hidden=false;fieldControl();(el('claim-search')||el('draft-value')).focus();};
el('draft-form').onsubmit=e=>{e.preventDefault();if(!el('buyer-confirmed').checked)return;if(!el('draft-value').value){status('Choose a catalog claim type before continuing.');return;}command('update',el('draft-field').value,el('draft-value').value);el('buyer-confirmed').checked=false;};
el('criteria-form').onsubmit=e=>{e.preventDefault();if(el('criteria-confirmed').checked)command('update','firmCriteria',el('firm-criteria').value);el('criteria-confirmed').checked=false;};
el('review-draft').onclick=()=>{if(el('brief-confirmed').checked)command('review');else status('Read back the required business fields and sample price and check full-brief confirmation first.');};
async function cancelCurrent(){if(inFlight)await inFlight;if(token)await command('cancel');}
el('cancel-draft').onclick=cancelCurrent;
el('reconnect-draft').onclick=()=>{if(!busy){if(catalog.length)connect();else initialize();}};
el('new-draft').onclick=async()=>{if(busy)return;if(token)await cancelCurrent();if(token){status('Clearing is not confirmed. Reconnect or leave; the session will expire.');return;}token=null;sessionStorage.removeItem(key);if(catalog.length)connect();else initialize();};
document.querySelectorAll('[data-leave-builder]').forEach(a=>a.addEventListener('click',async e=>{e.preventDefault();await cancelCurrent();location.href=a.href;}));
window.addEventListener('pagehide',()=>{clearTimeout(pollTimer);++generation;clearBrowserDrafts();token=null;sessionStorage.removeItem(key);});
window.addEventListener('pageshow',e=>{if(e.persisted){token=null;if(catalog.length)connect();else initialize();}});
void initialize();

export const getDraftSnapshot=()=>snapshot?structuredClone(snapshot):null;
export const reviewDraft=()=>command('review');
