window.DOMAIN_CONFIG={
  "DOMAIN_ID": "BHS",
  "DOMAIN_HOST": "buttholesause.com",
  "BRAND_NAME": "Butthole Sause",
  "VERTICAL": "food-drink",
  "PAGE_VERSION": "20260919-1",
  "PAGE_SLUG": "index",
  "CAMPAIGN_ID": "BHS_V1",
  "LEAD_SOURCE": "site_form",
  "ENDPOINT": "",
  "PHONE": "(619) 736-0356",
  "SUPPORT_EMAIL": "hello@buttholesause.com",
  "VOICE_ENABLED": false,
  "SMS_ENABLED": false,
  "GTM_ID": "GTM-N2KGSPKN",
  "GA4_MEASUREMENT_ID": "",
  "META_PIXEL_ID": "",
  "CONSENT_VERSION": "BHS_TCPA_2026-09-18_V1",
  "GTM_SERVER_CONTAINER_ID": "GTM-NMT76SV2",
  "GTM_SERVER_URL": "",
  "TIKTOK_PIXEL_ID": "",
  "GOOGLE_ADS_TAG_ID": "",
  "GOOGLE_ADS_CONVERSION_LABEL": "",
  "DOMAIN_ROLE": "acquisition_surface",
  "FIRM_VISIBLE": false,
  "ENVELOPE_DOMAIN": "",
  "RENDER_SERVICE": "bhs-site",
  "THANK_YOU_URL": "/thank-you.html"
};
