window.DOMAIN_CONFIG={
  "DOMAIN_ID": "DMA",
  "DOMAIN_HOST": "digitalmarketingapes.com",
  "BRAND_NAME": "Digital Marketing Apes",
  "VERTICAL": "b2b-agency",
  "PAGE_VERSION": "20260919-1",
  "PAGE_SLUG": "index",
  "CAMPAIGN_ID": "DMA_V1",
  "LEAD_SOURCE": "site_form",
  "ENDPOINT": "https://hook.us2.make.com/3simdd4xno0o9lh9jlsjdkc64570s3c4",
  "PHONE": "(619) 736-0356",
  "SUPPORT_EMAIL": "hello@digitalmarketingapes.com",
  "VOICE_ENABLED": false,
  "SMS_ENABLED": false,
  "GTM_ID": "GTM-WWD65KF",
  "GA4_MEASUREMENT_ID": "",
  "META_PIXEL_ID": "",
  "CONSENT_VERSION": "DMA_TCPA_2026-09-18_V1",
  "GTM_SERVER_CONTAINER_ID": "GTM-P955GDZ5",
  "GTM_SERVER_URL": "https://server-side-tagging-nn3socwquq-uc.a.run.app",
  "TIKTOK_PIXEL_ID": "",
  "GOOGLE_ADS_TAG_ID": "",
  "GOOGLE_ADS_CONVERSION_LABEL": "",
  "DOMAIN_ROLE": "acquisition_surface",
  "FIRM_VISIBLE": false,
  "ENVELOPE_DOMAIN": "",
  "RENDER_SERVICE": "dma-site",
  "THANK_YOU_URL": "/thank-you.html"
};
