window.DOMAIN_CONFIG={
  "DOMAIN_ID": "CGG",
  "DOMAIN_HOST": "crazygolfgame.com",
  "BRAND_NAME": "Crazy Golf Game",
  "VERTICAL": "sports",
  "PAGE_VERSION": "20260919-1",
  "PAGE_SLUG": "index",
  "CAMPAIGN_ID": "CGG_V1",
  "LEAD_SOURCE": "site_form",
  "ENDPOINT": "https://hook.us2.make.com/3simdd4xno0o9lh9jlsjdkc64570s3c4",
  "PHONE": "(619) 736-0356",
  "SUPPORT_EMAIL": "hello@crazygolfgame.com",
  "VOICE_ENABLED": false,
  "SMS_ENABLED": false,
  "GTM_ID": "GTM-K8TXN9",
  "GA4_MEASUREMENT_ID": "G-6W2RXNMMXR",
  "META_PIXEL_ID": "",
  "CONSENT_VERSION": "CGG_TCPA_2026-09-18_V1",
  "GTM_SERVER_CONTAINER_ID": "GTM-NMT76SV2",
  "GTM_SERVER_URL": "",
  "TIKTOK_PIXEL_ID": "",
  "GOOGLE_ADS_TAG_ID": "",
  "GOOGLE_ADS_CONVERSION_LABEL": "",
  "DOMAIN_ROLE": "acquisition_surface",
  "FIRM_VISIBLE": false,
  "ENVELOPE_DOMAIN": "",
  "RENDER_SERVICE": "cgg-site",
  "THANK_YOU_URL": "/thank-you.html"
};
