import {fileURLToPath} from 'node:url';import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {validateExpansion} from './validate-expansion.mjs';import {reviewConversation,countConversations} from './qualified-conversation-review.mjs';
const dir=path.dirname(fileURLToPath(import.meta.url));const baseline=validateExpansion(dir);
test('complete staged expansion preserves one cap, exact identities and default-off gates',()=>assert.equal(baseline.budget.planning_total_usd,5000));
for(const [name,edit] of [['unbounded funding',x=>x.budget.unlimited_spend_allowed=true],['Friday compression assumed',x=>x.budget.compressed_friday_cap_usd=5000],['deadline burn authorized',x=>x.budget.deadline_burn_authorized=true],['per-path money multiplied',x=>x.meta_website.paths[1].proposed_incremental_budget_usd=3000],['native callbacks released',x=>x.meta_native.callback_enabled=true],['native health collection',x=>x.meta_native.health_questions_allowed=true],['call-only recreated',x=>x.call_exploration.google.new_call_only_ad_allowed=true],['consumer hours inferred',x=>x.call_exploration.receiving_route.consumer_hours_approved=true],['BTL identity reused',x=>x.google_pmax_exploration.account_id='9455635555'],['sensitive signals',x=>x.google_pmax_exploration.audience_signals=['injury']],['signing guarantee',x=>x.objective.signed_target_is_guarantee=true],['feedback upload',x=>x.daily_review.platform_feedback_enabled=true]])test(`reject ${name}`,t=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'phillips-expansion-'));t.after(()=>fs.rmSync(d,{recursive:true,force:true}));const x=structuredClone(baseline);edit(x);fs.writeFileSync(path.join(d,'channel-expansion-review.json'),JSON.stringify(x));for(const f of ['launch-decision-review.md','qualified-conversation-review.mjs'])fs.copyFileSync(path.join(dir,f),path.join(d,f));assert.throws(()=>validateExpansion(d));});
const valid={lead_id:'synthetic-only',source_receipt_ref:'private-source',contact_permission:true,consent_receipt_ref:'private-consent',two_way_prospect_contact:true,contact_evidence_ref:'private-contact',human_reviewed:true,reviewer_ref:'private-reviewer',firm_criteria_agreed:true,human_confirmed_criteria_met:true,criteria_version:'firm-agreed-test-only',private_outcome_ref:'private-outcome'};
test('documented actual contact and human firm criteria count; no signing inferred',()=>assert.deepEqual(countConversations([valid,valid]),{qualified_live_conversations:1,signed:0,held_conflicting_lead_ids:[],platform_export_allowed:false}));
for(const field of ['contact_permission','two_way_prospect_contact','human_reviewed','firm_criteria_agreed','human_confirmed_criteria_met'])test(`missing ${field} cannot qualify`,()=>assert.equal(reviewConversation({...valid,[field]:false,ai_qualified:true,platform_conversion:true,call_attempted:true}).qualified_live_conversation,false));
test('opt-in/AI/call-attempt alone cannot count',()=>assert.equal(reviewConversation({lead_id:'synthetic',platform_conversion:true,ai_qualified:true,call_attempted:true}).qualified_live_conversation,false));
test('conflicting snapshots held rather than earliest positive chosen',()=>assert.deepEqual(countConversations([valid,{...valid,two_way_prospect_contact:false}]).held_conflicting_lead_ids,['synthetic-only']));
test('signed requires separate retainer proof and date, never Converted/sent',()=>{assert.equal(reviewConversation({...valid,status:'Converted',sent_date:'2026-10-05'}).signed,false);assert.equal(reviewConversation({...valid,retainer_executed:true,retainer_evidence_ref:'executed-test-only',retainer_executed_date:'2026-10-05'}).signed,true);assert.equal(reviewConversation({...valid,retainer_executed:true,retainer_evidence_ref:'executed-test-only',retainer_executed_date:'bad'}).signed,false);});

test('impossible retainer date is held',()=>assert.equal(reviewConversation({...valid,retainer_executed:true,retainer_evidence_ref:'executed-test-only',retainer_executed_date:'2026-02-31'}).signed,false));

test('conflicting source proof held even when both qualify',()=>assert.deepEqual(countConversations([valid,{...valid,source_receipt_ref:'different-private-source'}]).held_conflicting_lead_ids,['synthetic-only']));
