window.DOMAIN_CONFIG={
  "DOMAIN_ID": "H2M",
  "DOMAIN_HOST": "hair2makeup.com",
  "BRAND_NAME": "Hair 2 Makeup",
  "VERTICAL": "beauty",
  "PAGE_VERSION": "20260919-1",
  "PAGE_SLUG": "index",
  "CAMPAIGN_ID": "H2M_V1",
  "LEAD_SOURCE": "site_form",
  "ENDPOINT": "",
  "PHONE": "(619) 736-0356",
  "SUPPORT_EMAIL": "hello@hair2makeup.com",
  "VOICE_ENABLED": false,
  "SMS_ENABLED": false,
  "GTM_ID": "GTM-W8W9RSWL",
  "GA4_MEASUREMENT_ID": "",
  "META_PIXEL_ID": "",
  "CONSENT_VERSION": "H2M_TCPA_2026-09-18_V1",
  "GTM_SERVER_CONTAINER_ID": "GTM-NMT76SV2",
  "GTM_SERVER_URL": "",
  "TIKTOK_PIXEL_ID": "",
  "GOOGLE_ADS_TAG_ID": "",
  "GOOGLE_ADS_CONVERSION_LABEL": "",
  "DOMAIN_ROLE": "acquisition_surface",
  "FIRM_VISIBLE": false,
  "ENVELOPE_DOMAIN": "",
  "RENDER_SERVICE": "h2m-site",
  "THANK_YOU_URL": "/thank-you.html"
};
